** PART ONE Fundamental Techniques in Handling People
*** 1 "IF YOU WANT TO GATHER HONEY, DON'T KICK OVER THE BEEHIVE"

On May 7, 1931, the most sensational manhunt New York City had ever
known had come to its climax. After weeks of search, "Two Gun" Crowley
- the killer, the gunman who didn't smoke or drink - was at bay,
trapped in his sweetheart's apartment on West End Avenue.

One hundred and fifty policemen and detectives laid siege to his
top-fioor hideway. They chopped holes in the roof; they tried to smoke
out Crowley, the "cop killer," with teargas. Then they mounted their
machine guns on surrounding buildings, and for more than an hour one
of New York's fine residential areas reverberated with the crack of
pistol fire and the rut-tat-tat of machine guns. Crowley, crouching
behind an overstuffed chair, fired incessantly at the police. Ten
thousand excited people watched the battle. Nothing like it ever been
seen before on the sidewalks of New York.

When Crowley was captured. Police Commissioner E. P. Mulrooney
declared that the two-gun desperado was one of the most dangerous
criminals ever encountered in the history of New York. "He will kill,"
said the Commissioner, "at the drop of a feather."

But how did "Two Gun" Crowley regard himself? We know, because while
the police were firing into his apartment, he wrote a letter addressed
"To whom it may concern, " And, as he wrote, the blood fiowing from
his wounds left a crimson trail on the paper. In this letter Crowley
said: "Under my coat is a weary heart, but a kind one - one that would
do nobody any harm."

A short time before this, Crowley had been having a necking party with
his girl friend on a country road out on Long Island. Suddenly a
policeman walked up to the car and said: "Let me see your license."

Without saying a word, Crowley drew his gun and cut the policeman down
with a shower of lead. As the dying

officer fell, Crowley leaped out of the car, grabbed the officer's
revolver, and fired another bullet into the prostrate body. And that
was the killer who said: "Under my coat is a weary heart, but a kind
one - one that would do nobody any harm.'

Crowley was sentenced to the electric chair. When he arrived at the
death house in Sing Sing, did he say, "This is what I get for killing
people"? No, he said: "This is what I get for defending myself"

The point of the story is this: "Two Gun" Crowley didn't blame himself
for anything.

Is that an unusual attitude among criminals? If you think so, listen
to this:

"I have spent the best years of my life giving people the lighter
pleasures, helping them have a good time, and all I get is abuse, the
existence of a hunted man."

That's Al Capone speaking. Yes, America's most notorious Public Enemy-
the most sinister gang leader who ever shot up Chicago. Capone didn't
condemn himself He actually regarded himself as a public benefactor -
an unappreciated and misunderstood public benefactor.

And so did Dutch Schultz before he crumpled up under gangster bullets
in Newark. Dutch Schultz, one of New York's most notorious rats, said
in a newspaper interview that he was a public benefactor. And he
believed it.

I have had some interesting correspondence with Lewis Lawes, who was
warden of New York's infamous Sing Sing prison for many years, on this
subject, and he declared that "few of the criminals in Sing Sing
regard themselves as bad men. They are just as human as you and I. So
they rationalize, they explain. They can tell you why they had to
crack a safe or be quick on the trigger finger. Most of them attempt
by a form of reasoning, fallacious or logical, to justify their
antisocial acts even to themselves, consequently stoutly maintaining
that they should never have been imprisoned at all."

If Al Capone, "Two Gun" Crowley, Dutch Schultz,

and the desperate men and women behind prison walls don't blame
themselves for anything - what about the people with whom you and I
come in contact?

John Wanamaker, founder of the stores that bear his name, once
confessed: "I learned thirty years ago that it is foolish to scold. I
have enough trouble overcoming my own limitations without fretting
over the fact that God has not seen fit to distribute evenly the gift
of intelligence."

Wanamaker learned this lesson early, but I personally had to blunder
through this old world for a third of a century before it even began
to dawn upon me that ninety-nine times out of a hundred, people don't
criticize themselves for anything, no matter how wrong it may be.

Criticism is ftitile because it puts a person on the defensive and
usually makes him strive to justify himself Criticism is dangerous,
because it wounds a person's precious pride, hurts his sense of
importance, and arouses resentment.

B. F. Skinner, the world-famous psychologist, proved through his
experiments that an animal rewarded for good behavior will learn much
more rapidly and retain what it learns far more effectively than an
animal punished for bad behavior. Later studies have shown that the
same applies to humans. By criticizing, we do not make lasting changes
and often incur resentment.

Hans Selye, another great psychologist, said, "As

much as we thirst for approval, we dread condemnation,"

The resentment that criticism engenders can demoralize employees,
family members and friends, and still not correct the situation that
has been condemned.

George B. Johnston of Enid, Oklahoma, is the safety

coordinator for an engineering company. One of his re-sponsibilities

is to see that employees wear their hard

hats whenever they are on the job in the field. He reported

that whenever he came across workers who were

not wearing hard hats, he would tell them with a lot of

authority of the regulation and that they must comply.

As a result he would get sullen acceptance, and often

after he left, the workers would remove the hats.

He decided to try a different approach. The next time he found some of
the workers not wearing their hard hat, he asked if the hats were
uncomfortable or did not fit properly. Then he reminded the men in a
pleasant tone of voice that the hat was designed to protect them from
injury and suggested that it always be worn on the job. The result was
increased compliance with the regulation with no resentment or
emotional upset.

You will find examples of the futility of criticism bristling

on a thousand pages of history. Take, for example,

the famous quarrel between Theodore Roosevelt and

President Taft - a quarrel that split the Republican

party, put Woodrow Wilson in the White House, and

wrote bold, luminous lines across the First World War

and altered the fiow of history. Let's review the facts

quickly. When Theodore Roosevelt stepped out of the

White House in 1908, he supported Taft, who was

elected President. Then Theodore Roosevelt went off to

Africa to shoot lions. When he returned, he exploded.

He denounced Taft for his conservatism, tried to secure

the nomination for a third term himself, formed the Bull

Moose party, and all but demolished the G.O.P. In the

election that followed, William Howard Taft and the Republican

party carried only two states - Vermont and

Utah. The most disastrous defeat the party had ever

known.

Theodore Roosevelt blamed Taft, but did President Taft blame himself?
Of course not. With tears in his eyes, Taft said: "I don't see how I
could have done any differently from what I have."

Who was to blame? Roosevelt or Taft? Frankly, I don't know, and I
don't care. The point I am trying to make is that all of Theodore
Roosevelt's criticism didn't persuade Taft that he was wrong. It
merely made Taft strive to justify himself and to reiterate with tears
in his eyes: "I don't see how I could have done any differently from
what I have."

Or, take the Teapot Dome oil scandal. It kept the newspapers ringing
with indignation in the early 1920s. It rocked the nation! Within the
memory of living men.

nothing like it had ever happened before in American public life. Here
are the bare facts of the scandal: Albert B. Fall, secretary of the
interior in Harding's cabinet, was entrusted with the leasing of
government oil reserves at Elk Hill and Teapot Dome - oil reserves
that had been set aside for the future use of the Navy. Did secretary
Fall permit competitive bidding? No sir. He handed the fat, juicy
contract outright to his friend Edward L. Doheny. And what did Doheny
do? He gave Secretary Fall what he was pleased to call a "loan" of one
hundred thousand dollars. Then, in a high-handed manner. Secretary
Fall ordered United States Marines into the district to drive off
competitors whose adjacent wells were sapping oil out of the Elk Hill
reserves. These competitors, driven off their ground at the ends of
guns and bayonets, rushed into court - and blew the lid off the Teapot
Dome scandal. A stench arose so vile that it ruined the Harding
Administration, nauseated an entire nation, threatened to wreck the
Republican party, and put Albert B. Fall behind prison bars.

Fall was condemned viciously - condemned as few men in public life
have ever been. Did he repent? Never! Years later Herbert Hoover
intimated in a public speech that President Harding's death had been
due to mental anxiety and worry because a friend had betrayed him.
When Mrs. Fall heard that, she sprang from her chair, she wept, she
shook her fists at fate and screamed: "What! Harding betrayed by Fall?
No! My husband never betrayed anyone. This whole house full of gold
would not tempt my husband to do wrong. He is the one who has been
betrayed and led to the slaughter and crucified."

There you are; human nature in action, wrongdoers, blaming everybody
but themselves. We are all like that. So when you and I are tempted to
criticize someone tomorrow, let's remember Al Capone, "Two Gun"
Crowley and Albert Fall. Let's realize that criticisms are like homing
pigeons. They always return home. Let's realize that the person we are
going to correct and condemn will probably justify himself or herself,
and condemn us in return; or, like the gentle Taft, will say: "I don't
see how I could have done any differently from what I have."

On the morning of April 15, 1865, Abraham Lincoln

lay dying in a hall bedroom of a cheap lodging house directly across
the street from Ford's Theater, where John Wilkes Booth had shot him.
Lincoln's long body lay stretched diagonally across a sagging bed that
was too short for him. A cheap reproduction of Rosa Bonheur's famous
painting The Horse Fair hung above the bed, and a dismal gas jet
flickered yellow light.

As Lincoln lay dying. Secretary of War Stanton said, "There lies the
most perfect ruler of men that the world has ever seen."

What was the secret of Lincoln's success in dealing with people? I
studied the life of Abraham Lincoln for ten years and devoted all of
three years to writing and rewriting a book entitled Lincoln the
Unknown. I believe I have made as detailed and exhaustive a study of
Lincoln's personality and home life as it is possible for any being to
make. I made a special study of Lincoln's method of dealing with
people. Did he indulge in criticism? Oh, yes. As a young man in the
Pigeon Creek Valley of Indiana, he not only criticized but he wrote
letters and poems ridiculing people and dropped these letters on the
country roads where they were sure to be found. One of these letters
aroused resentments that burned for a lifetime.

Even after Lincoln had become a practicing lawyer in Springfield,
Illinois, he attacked his opponents openly in letters published in the
newspapers. But he did this just once too often.

In the autumn of 1842 he ridiculed a vain, pugnacious politician by
the name of James Shields. Lincoln lamned him through an anonymous
letter published in Springfield Journal. The town roared with
laughter. Shields, sensitive and proud, boiled with indignation. He
found out who wrote the letter, leaped on his horse, started after
Lincoln, and challenged him to fight a duel. Lincoln didn't want to
fight. He was opposed to dueling, but he couldn't get out of it and
save his honor. He was given the choice of weapons. Since he had very
long arms, he chose cavalry broadswords and took lessons in sword
fighting from a West Point graduate; and, on the appointed day, he and
Shields met on a sandbar in the Mississippi River, prepared to fight
to the death; but, at

the last minute, their seconds interrupted and stopped the duel.

That was the most lurid personal incident in Lincoln's life. It taught
him an invaluable lesson in the art of dealing with people. Never
again did he write an insulting letter. Never again did he ridicule
anyone. And from that time on, he almost never criticized anybody for
anything.

Time after time, during the Civil War, Lincoln put a new general at
the head of the Army of the Potomac, and each one in turn - McClellan,
Pope, Burnside, Hooker, Meade - blundered tragically and drove Lincoln
to pacing the floor in despair. Half the nation savagely condemned
these incompetent generals, but Lincoln, "with malice toward none,
with charity for all," held his peace. One of his favorite quotations
was "Judge not, that ye be not judged."

And when Mrs. Lincoln and others spoke harshly of the southern people,
Lincoln replied: "Don't criticize them; they are just what we would be
under similar circumstances."

Yet if any man ever had occasion to criticize, surely it was Lincoln.
Let's take just one illustration:

The Battle of Gettysburg was fought during the first

three days of July 1863. During the night of July 4, Lee

began to retreat southward while storm clouds deluged

the country with rain. When Lee reached the Potomac

with his defeated army, he found a swollen, impassable

river in front of him, and a victorious Union Army behind

him. Lee was in a trap. He couldn't escape. Lincoln

saw that. Here was a golden, heaven-sent opportunity-

the opportunity to capture Lee's army and end the war

immediately. So, with a surge of high hope, Lincoln ordered

Meade not to call a council of war but to attack

Lee immediately. Lincoln telegraphed his orders and

then sent a special messenger to Meade demanding immediate

action.

And what did General Meade do? He did the very opposite of what he was
told to do. He called a council of war in direct violation of
Lincoln's orders. He hesitated. He procrastinated. He telegraphed all
manner of

excuses. He refused point-blank to attack Lee. Finally the waters
receded and Lee escaped over the Potomac with his forces.

Lincoln was furious, " What does this mean?" Lincoln cried to his son
Robert. "Great God! What does this mean? We had them within our grasp,
and had only to stretch forth our hands and they were ours; yet
nothing that I could say or do could make the army move. Under the
circumstances, almost any general could have defeated Lee. If I had
gone up there, I could have whipped him myself"

In bitter disappointment, Lincoln sat down and wrote Meade this
letter. And remember, at this period of his life Lincoln was extremely
conservative and restrained in his phraseology. So this letter coming
from Lincoln in 1863 was tantamount to the severest rebuke.

My dear General,

I do not believe you appreciate the magnitude of the misfortune
involved in Lee's escape. He was within our easy grasp, and to have
closed upon him would, in connection With our other late successes,
have ended the war. As it is, the war will be prolonged indefinitely.
If you could not safely attack Lee last Monday, how can you possibly
do so south of the river, when you can take with you very few-no more
than two-thirds of the force you then had in hand? It would be
unreasonable to expect and I do not expect that you can now effect
much. Your golden opportunity is gone, and I am distressed
immeasurably because of it.

What do you suppose Meade did when he read the letter?

Meade never saw that letter. Lincoln never mailed it. It was found
among his papers after his death.

My guess is - and this is only a guess - that after writing that
letter, Lincoln looked out of the window and said to himself, "Just a
minute. Maybe I ought not to be so hasty. It is easy enough for me to
sit here in the quiet of the White House and order Meade to attack;
but if I had been up at Gettysburg, and if I had seen as much blood as
Meade has seen during the last week, and if my

ears had been pierced with the screams and shrieks of the wounded and
dying, maybe I wouldn't be so anxious to attack either. If I had
Meade's timid temperament, perhaps I would have done just what he had
done. Anyhow, it is water under the bridge now. If I send this letter,
it will relieve my feelings, but it will make Meade try to justify
himself It will make him condemn me. It will arouse hard feelings,
impair all his further usefulness as a commander, and perhaps force
him to resign from the army."

So, as I have already said, Lincoln put the letter aside,

for he had learned by bitter experience that sharp criticisms

and rebukes almost invariably end in futility.

Theodore Roosevelt said that when he, as President, was confronted
with a perplexing problem, he used to lean back and look up at a large
painting of Lincoln which hung above his desk in the White House and
ask himself, "What would Lincoln do if he were in my shoes? How would
he solve this problem?"

The next time we are tempted to admonish somebody, let's pull a
five-dollar bill out of our pocket, look at Lincoln's picture on the
bill, and ask. "How would Lincoln handle this problem if he had it?"

Mark Twain lost his temper occasionally and wrote letters that turned
the Paper brown. For example, he once wrote to a man who had aroused
his ire: "The thing for you is a burial permit. You have only to speak
and I will see that you get it." On another occasion he wrote to an
editor about a proofreader's attempts to "improve my spelling and
punctuation." He ordered: "Set the matter according to my copy
hereafter and see that the proofreader retains his suggestions in the
mush of his decayed brain."

The writing of these stinging letters made Mark Twain feel better.
They allowed him to blow off steam, and the letters didn't do any real
harm, because Mark's wife secretly lifted them out of the mail. They
were never sent.

Do you know someone you would like to change and regulate and improve?
Good! That is fine. I am all in

favor of it, But why not begin on yourself? From a purely selfish
standpoint, that is a lot more profitable than trying to improve
others - yes, and a lot less dangerous. "Don't complain about the snow
on your neighbor's roof," said Confucius, "when your own doorstep is
unclean."

When I was still young and trying hard to impress people, I wrote a
foolish letter to Richard Harding Davis, an author who once loomed
large on the literary horizon of America. I was preparing a magazine
article about authors, and I asked Davis to tell me about his method
of work. A few weeks earlier, I had received a letter from someone
with this notation at the bottom: "Dictated but not read." I was quite
impressed. I felt that the writer must be very big and busy and
important. I wasn't the slightest bit busy, but I was eager to make an
impression on Richard Harding Davis, so I ended my short note with the
words: "Dictated but not read."

He never troubled to answer the letter. He simply returned it to me
with this scribbled across the bottom: "Your bad manners are exceeded
only by your bad manners." True, I had blundered, and perhaps I
deserved this rebuke. But, being human, I resented it. I resented it
so sharply that when I read of the death of Richard Harding Davis ten
years later, the one thought that still persisted in my mind -1 am
ashamed to admit - was the hurt he had given me.

If you and I want to stir up a resentment tomorrow that may rankle
across the decades and endure until death, just let us indulge in a
little stinging criticism-no matter how certain we are that it is
justified.

When dealing with people, let us remember we are not dealing with
creatures of logic. We are dealing with creatures of emotion,
creatures bristling with prejudices and motivated by pride and vanity.

Bitter criticism caused the sensitive Thomas Hardy, one of the finest
novelists ever to enrich English literature, to give up forever the
writing of fiction. Criticism drove Thomas Chatterton, the English
poet, to suicide.

Benjamin Franklin, tactless in his youth, became so diplomatic, so
adroit at handling people, that he was

made American Ambassador to France. The secret of his success? "I will
speak ill of no man," he said, " . . and speak all the good I know of
everybody."

Any fool can criticize, condemn and complain - and most fools do.

But it takes character and self-control to be under-standing and
forgiving.

"A great man shows his greatness," said Carlyle, "by the way he treats
little men."

Bob Hoover, a famous test pilot and frequent per-former

at air shows, was returning to his home in Los

Angeles from an air show in San Diego. As described in

the magazine Flight Operations, at three hundred feet

in the air, both engines suddenly stopped. By deft maneuvering

he managed to land the plane, but it was

badly damaged although nobody was hurt.

Hoover's first act after the emergency landing was to inspect the
airplane's fuel. Just as he suspected, the World War II propeller
plane he had been flying had been fueled with jet fuel rather than
gasoline.

Upon returning to the airport, he asked to see the mechanic who had
serviced his airplane. The young man was sick with the agony of his
mistake. Tears streamed down his face as Hoover approached. He had
just caused the loss of a very expensive plane and could have caused
the loss of three lives as well.

You can imagine Hoover's anger. One could anticipate the
tongue-lashing that this proud and precise pilot would unleash for
that carelessness. But Hoover didn't scold the mechanic; he didn't
even criticize him. Instead, he put his big arm around the man's
shoulder and said, "To show you I'm sure that you'll never do this
again, I want you to service my F-51 tomorrow."

Often parents are tempted to criticize their children.

You would expect me to say "don't." But I will not, I am

merely going to say, "Before you criticize them, read

one of the classics of American journalism, 'Father Forgets.' "

It originally appeared as an editorial in the People's

Home Journnl. We are reprinting it here with the author's permission,
as condensed in the Reader's Digest:

"Father Forgets" is one of those httle pieces which-dashed of in a
moment of sincere feeling - strikes an echoing chord in so many
readers as to become a perenial reprint favorite. Since its first
appearance, "Father Forgets" has been reproduced, writes the author,
W, Livingston Larned, "in hundreds of magazines and house organs, and
in newspapers the country over. It has been reprinted almost as
extensively in many foreign languages. I have given personal
permission to thousands who wished to read it from school, church, and
lecture platforms. It has been 'on the air' on countless occasions and
programs. Oddly enough, college periodicals have used it, and
high-school magazines. Sometimes a little piece seems mysteriously to
'click.' This one certainly did."

FATHER FORGETS

W. Livingston Larned

Listen, son: I am saying this as you lie asleep, one little paw
crumpled under your cheek and the blond curls stickily wet on your
damp forehead. I have stolen into your room alone. Just a few minutes
ago, as I sat reading my paper in the library, a stifling wave of
remorse swept over me. Guiltily I came to your bedside.

There are the things I was thinking, son: I had been cross to you. I
scolded you as you were dressing for school because you gave your face
merely a dab with a towel. I took you to task for not cleaning your
shoes. I called out angrily when you threw some of your things on the
floor.

At breakfast I found fault, too. You spilled things. You gulped down
your food. You put your elbows on the table. You spread butter too
thick on your bread. And as you started off to play and I made for my
train, you turned and waved a hand and called, "Goodbye, Daddy!" and I
frowned, and said in reply, "Hold your shoulders back!"

Then it began all over again in the late afternoon. As I came up the
road I spied you, down on your knees, playing marbles. There were
holes in your stockings. I humiliated

you before your boyfriends by marching you ahead of me to the house.
Stockings were expensive - and if you had to

buy them you would be more careful! Imagine that, son, from a father!

Do you remember, later, when I was reading in the library, how you
came in timidly, with a sort of hurt look in your eyes? When I glanced
up over my paper, impatient at the interruption, you hesitated at the
door. "What is it you want?" I snapped.

You said nothing, but ran across in one tempestuous plunge, and threw
your arms around my neck and kissed me, and your small arms tightened
with an affection that God had set blooming in your heart and which
even neglect could not wither. And then you were gone, pattering up
the stairs.

Well, son, it was shortly afterwards that my paper slipped from my
hands and a terrible sickening fear came over me. What has habit been
doing to me? The habit of finding fault, of reprimanding - this was my
reward to you for being a boy. It was not that I did not love you; it
was that I expected too much of youth. I was measuring you by the
yardstick of my own years.

And there was so much that was good and fine and true in your
character. The little heart of you was as big as the dawn itself over
the wide hills. This was shown by your spontaneous impulse to rush in
and kiss me good night. Nothing else matters tonight, son. I have come
to your bed-side in the darkness, and I have knelt there, ashamed!

It is a feeble atonement; I know you would not understand these things
if I told them to you during your waking hours. But tomorrow I will be
a real daddy! I will chum with you, and suffer when you suffer, and
laugh when you laugh. I will bite my tongue when impatient words come.
I will keep saying as if it were a ritual: "He is nothing but a boy -
a little boy!"

I am afraid I have visualized you as a man. Yet as I see you now, son,
crumpled and weary in your cot, I see that you are still a baby.
Yesterday you were in your mother's arms, your head on her shoulder. I
have asked too much.

too much.

Instead of condemning people, let's try to understand them. Let's try
to figure out why they do what they do. That's a lot more profitable
and intriguing than criticism; and it breeds sympathy, tolerance and
kindness. "To know all is to forgive all."

As Dr. Johnson said: "God himself, sir, does not propose to judge man
until the end of his days."

Why should you and I?

PRINCIPLE 1 Don't criticize, condemn or complain.
*** THE BIG SECRET OF DEALING WITH PEOPLE

There is only one way under high heaven to get anybody

to do anything. Did you ever stop to think of that? Yes,

just one way. And that is by making the other person want to do it.

Remember, there is no other way.

Of course, you can make someone want to give you his watch by sticking
a revolver in his ribs. YOU can make your employees give you
cooperation - until your back is turned - by threatening to fire them.
You can make a child do what you want it to do by a whip or a threat.
But these crude methods have sharply undesirable repercussions.

The only way I can get you to do anything is by giving you what you
want.

What do you want?

Sigmund Freud said that everything you and I do

springs from two motives: the sex urge and the desire to be great.

John Dewey, one of America's most profound philosophers, phrased it a
bit differently. Dr. Dewey said that the deepest urge in human nature
is "the desire to be important." Remember that phrase: "the desire to
be important." It is significant. You are going to hear a lot about it
in this book.

What do you want? Not many things, but the few that you do wish, you
crave with an insistence that will not be denied. Some of the things
most people want include:

1. Health and the preservation of life.

2. Food.

3. Sleep.

4. Money and the things money will buy.

5. Life in the hereafter.

6. Sexual gratification.

7. The well-being of our children.

8. A feeling of importance.

Almost all these wants are usually gratified-all except one. But there
is one longing - almost as deep, almost as imperious, as the desire
for food or sleep - which is seldom gratified. It is what Freud calls
"the desire to be great." It is what Dewey calls the "desire to be
important."

Lincoln once began a letter saying: "Everybody likes

a compliment." William James said: "The deepest principle

in human nature is the craving to be appreciated."

He didn't speak, mind you, of the "wish" or the "desire"

or the "longing" to be appreciated. He said the "craving"

to be appreciated.

Here is a gnawing and unfaltering human hunger, and the rare
individual who honestly satisfies this heart hunger will hold people
in the palm of his or her hand and "even the undertaker will be sorry
when he dies."

The desire for a feeling of importance is one of the chief
distinguishing differences between mankind and

the animals. To illustrate: When I was a farm boy out in Missouri, my
father bred fine Duroc-Jersey hogs and . pedigreed white - faced
cattle. We used to exhibit our hogs and white-faced cattle at the
country fairs and live-stock shows throughout the Middle West. We won
first prizes by the score. My father pinned his blue ribbons on a
sheet of white muslin, and when friends or visitors came to the house,
he would get out the long sheet of muslin. He would hold one end and I
would hold the other while he exhibited the blue ribbons.

The hogs didn't care about the ribbons they had won.

But Father did. These prizes gave him a feeling of importance.

If our ancestors hadn't had this fiaming urge for a feeling of
importance, civilization would have been impossible. Without it, we
should have been just about like animals.

It was this desire for a feeling of importance that led an uneducated,
poverty-stricken grocery clerk to study some law books he found in the
bottom of a barrel of household plunder that he had bought for fifty
cents. You have probably heard of this grocery clerk. His name was
Lincoln.

It was this desire for a feeling of importance that inspired Dickens
to write his immortal novels. This desire inspired Sir Christoper Wren
to design his symphonies in stone. This desire made Rockefeller amass
millions that he never spent! And this same desire made the richest
family in your town build a house far too large for its requirements.

This desire makes you want to wear the latest styles, drive the latest
cars, and talk about your brilliant children.

It is this desire that lures many boys and girls into joining gangs
and engaging in criminal activities. The average young criminal,
according to E. P. Mulrooney, onetime police commissioner of New York,
is filled with ego, and his first request after arrest is for those
lurid newspapers that make him out a hero. The disagreeable prospect
of serving time seems remote so long as he can gloat over his likeness
sharing space with pictures of sports figures, movie and TV stars and
politicians.

If you tell me how you get your feeling of importance, I'll tell you
what you are. That determines your character. That is the most
significant thing about you. For example, John D. Rockefeller got his
feeling of importance by giving money to erect a modern hospital in
Peking, China, to care for millions of poor people whom he had never
seen and never would see. Dillinger, on the other hand, got his
feeling of importance by being a bandit, a bank robber and killer.
When the FBI agents were hunting him, he dashed into a farmhouse up in
Minnesota and said, "I'm Dillinger!" He was proud of the fact that he
was Public Enemy Number One. "I'm not going to hurt you, but I'm
Dillinger!" he said.

Yes, the one significant difference between Dillinger

and Rockefeller is how they got their feeling of importance.

History sparkles with amusing examples of famous people struggling for
a feeling of importance. Even George Washington wanted to be called
"His Mightiness, the President of the United States"; and Columbus
pleaded for the title "Admiral of the Ocean and Viceroy of India."
Catherine the Great refused to open letters that were not addressed to
"Her Imperial Majesty"; and Mrs. Lincoln, in the White House, turned
upon Mrs. Grant like a tigress and shouted, "How dare you be seated in
my presence until I invite you!"

Our millionaires helped finance Admiral Byrd's expedition to the
Antarctic in 1928 with the understanding that ranges of icy mountains
would be named after them; and Victor Hugo aspired to have nothing
less than the city of Paris renamed in his honor. Even Shakespeare,
mightiest of the mighty, tried to add luster to his name by procuring
a coat of arms for his family.

People sometimes became invalids in order to win sympathy and
attention, and get a feeling of importance. For example, take Mrs.
McKinley. She got a feeling of importance by forcing her husband, the
President of the United States, to neglect important affairs of state
while he reclined on the bed beside her for hours at a time, his arm
about her, soothing her to sleep. She fed her gnawing desire for
attention by insisting that he remain with her while she was having
her teeth fixed, and once created

a stormy scene when he had to leave her alone with the dentist while
he kept an appointment with John Hay, his secretary of state.

The writer Mary Roberts Rinehart once told me of a bright, vigorous
young woman who became an invalid in order to get a feeling of
importance. "One day," said Mrs. Rinehart, "this woman had been
obliged to face something, her age perhaps. The lonely years were
stretching ahead and there was little left for her to anticipate.

"She took to her bed; and for ten years her old mother traveled to the
third floor and back, carrying trays, nursing her. Then one day the
old mother, weary with service, lay down and died. For some weeks, the
invalid languished; then she got up, put on her clothing, and resumed
living again."

Some authorities declare that people may actually go insane in order
to find, in the dreamland of insanity, the feeling of importance that
has been denied them in the harsh world of reality. There are more
patients suffering from mental diseases in the United States than from
all other diseases combined.

What is the cause of insanity?

Nobody can answer such a sweeping question, but we know that certain
diseases, such as syphilis, break down and destroy the brain cells and
result in insanity. In fact, about one-half of all mental diseases can
be attributed to such physical causes as brain lesions, alcohol,
toxins and injuries. But the other half - and this is the appalling
part of the story - the other half of the people who go insane
apparently have nothing organically wrong with their brain cells. In
post-mortem examinations, when their brain tissues are studied under
the highest-powered microscopes, these tissues are found to be
apparently just as healthy as yours and mine.

Why do these people go insane?

I put that question to the head physician of one of our most important
psychiatric hospitals. This doctor, who has received the highest
honors and the most coveted awards for his knowledge of this subject,
told me frankly

that he didn't know why people went insane. Nobody knows for sure But
he did say that many people who go insane find in insanity a feeling
of importance that they were unable to achieve in the world of
reality. Then he told me this story:

"I have a patient right now whose marriage proved to be a tragedy. She
wanted love, sexual gratification, children and social prestige, but
life blasted all her hopes. Her husband didn't love her. He refused
even to eat with her and forced her to serve his meals in his room
upstairs. She had no children, no social standing. She went insane;
and, in her imagination, she divorced her husband and resumed her
maiden name. She now believes she has married into English
aristocracy, and she insists on being called Lady Smith.

"And as for children, she imagines now that she has had a new child
every night. Each time I call on her she says: 'Doctor, I had a baby
last night.' "

Life once wrecked all her dream ships on the sharp rocks of reality;
but in the sunny, fantasy isles of insanity, all her barkentines race
into port with canvas billowing and winds singing through the masts.

" Tragic? Oh, I don't know. Her physician said to me: If I could
stretch out my hand and restore her sanity, I wouldn't do it. She's
much happier as she is."

If some people are so hungry for a feeling of importance that they
actually go insane to get it, imagine what miracle you and I can
achieve by giving people honest appreciation this side of insanity.

One of the first people in American business to be paid a salary of
over a million dollars a year (when there was no income tax and a
person earning fifty dollars a week was considered well off) was
Charles Schwab, He had been picked by Andrew Carnegie to become the
first president of the newly formed United States Steel Company in
1921, when Schwab was only thirty-eight years old. (Schwab later left
U.S. Steel to take over the then-troubled Bethlehem Steel Company, and
he rebuilt it into one of the most profitable companies in America.)

Why did Andrew Carnegie pay a million dollars a year, or more than
three thousand dollars a day, to Charles Schwab? Why? Because Schwab
was a genius? No. Because he knew more about the manufacture of steel
than other people? Nonsense. Charles Schwab told me himself that he
had many men working for him who knew more about the manufacture of
steel than he did.

Schwab says that he was paid this salary largely because of his
ability to deal with people. I asked him how he did it. Here is his
secret set down in his own words - words that ought to be cast in
eternal bronze and hung in every home and school, every shop and
office in the land - words that children ought to memorize instead of
wasting their time memorizing the conjugation of Latin verbs or the
amount of the annual rainfall in Brazil - words that will all but
transform your life and mine if we will only live them:

"I consider my ability to arouse enthusiasm among my people," said
Schwab, "the greatest asset I possess, and the way to develop the best
that is in a person is by appreciation and encouragement.

"There is nothing else that so kills the ambitions of a person as
criticisms from superiors. I never criticize anyone. I believe in
giving a person incentive to work. So I am anxious to praise but loath
to find fault. If I like anything, / am hearty in my approbation and
lavish in my praise. "

That is what Schwab did. But what do average people do? The exact
opposite. If they don't like a thing, they bawl out their
subordinates; if they do like it, they say nothing. As the old couplet
says: "Once I did bad and that I heard ever/Twice I did good, but that
I heard never."

"In my wide association in life, meeting with many and great people in
various parts of the world," Schwab declared, "I have yet to find the
person, however great or exalted his station, who did not do better
work and put forth greater effort under a spirit of approval than he
would ever do under a spirit of criticism."

That he said, frankly, was one of the outstanding reasons

for the phenomenal success of Andrew Carnegie. Carnegie praised his
associates pubhcly as well as pr-vately.

Carnegie wanted to praise his assistants even on his tombstone. He
wrote an epitaph for himself which read: "Here lies one who knew how
to get around him men who were cleverer than himself"

Sincere appreciation was one of the secrets of the first

John D. Rockefeller's success in handling men. For example,

when one of his partners, Edward T. Bedford,

lost a million dollars for the firm by a bad buy in South

America, John D. might have criticized; but he knew

Bedford had done his best - and the incident was

closed. So Rockefeller found something to praise; he

congratulated Bedford because he had been able to save

60 percent of the money he had invested. "That's splendid,"

said Rockefeller. "We don't always do as well as

that upstairs."

I have among my clippings a story that I know never happened, but it
illustrates a truth, so I'll repeat it:

According to this silly story, a farm woman, at the end of a heavy
day's work, set before her menfolks a heaping pile of hay. And when
they indignantly demanded whether she had gone crazy, she replied:
"Why, how did I know you'd notice? I've been cooking for you men for
the last twenty years and in all that time I ain't heard no word to
let me know you wasn't just eating hay."

When a study was made a few years ago on runaway wives, what do you
think was discovered to be the main reason wives ran away? It was
"lack of appreciation." And I'd bet that a similar study made of
runaway husbands would come out the same way. We often take our
spouses so much for granted that we never let them know we appreciate
them.

A member of one of our classes told of a request made by his wife. She
and a group of other women in her church were involved in a
self-improvement program. She asked her husband to help her by listing
six things he believed she could do to help her become a better wife.
He reported to the class: "I was surprised by such a request. Frankly,
it would have been easy for me to list

six things I would like to change about her - my heavens, she could
have listed a thousand things she would like to change about me - but
I didn't. I said to her, 'Let me think about it and give you an answer
in the morning.'

"The next morning I got up very early and called the florist and had
them send six red roses to my wife with a note saying: 'I can't think
of six things I would like to change about you. I love you the way you
are.'

"When I arrived at home that evening, who do you think greeted me at
the door: That's right. My wife! She was almost in tears. Needless to
say, I was extremely glad I had not criticized her as she had
requested.

"The following Sunday at church, after she had reported the results of
her assignment, several women with whom she had been studying came up
to me and said, 'That was the most considerate thing I have ever
heard.' It was then I realized the power of appreciation."

Florenz Ziegfeld, the most spectacular producer who ever dazzled
Broadway, gained his reputation by his subtle ability to "glorify the
American girl." Time after time, he took drab little creatures that no
one ever looked at twice and transformed them on the stage into
glamorous visions of mystery and seduction. Knowing the value of
appreciation and confidence, he made women feel beautiful by the sheer
power of his gallantry and consideration. He was practical: he raised
the salary of chorus girls from thirty dollars a week to as high as
one hundred and seventy-five. And he was also chivalrous; on opening
night at the Follies, he sent telegrams to the stars in the cast, and
he deluged every chorus girl in the show with American Beauty roses.

I once succumbed to the fad of fasting and went for six days and
nights without eating. It wasn't difficult. I was less hungry at the
end of the sixth day than I was at the end of the second. Yet I know,
as you know, people who would think they had committed a crime if they
let their families or employees go for six days without food; but they
will let them go for six days, and six weeks, and sometimes sixty
years without giving them the hearty appreciation that they crave
almost as much as they crave food.

When Alfred Lunt, one of the great actors of his time, played the
leading role in Reunion in Vienna, he said, "There is nothing I need
so much as nourishment for my self-esteem."

We nourish the bodies of our children and friends and employees, but
how seldom do we nourish their selfesteem? We provide them with roast
beef and potatoes to build energy, but we neglect to give them kind
words of appreciation that would sing in their memories for years like
the music of the morning stars.

Paul Harvey, in one of his radio broadcasts, "The Rest of the Story,"
told how showing sincere appreciation can change a person's life. He
reported that years ago a teacher in Detroit asked Stevie Morris to
help her find a mouse that was lost in the classroom. You see, she
appreciated the fact that nature had given Stevie something no one
else in the room had. Nature had given Stevie a remarkable pair of
ears to compensate for his blind eyes. But this was really the first
time Stevie had been shown appreciation for those talented ears. Now,
years later, he says that this act of appreciation was the beginning
of a new life. You see, from that time on he developed his gift of
hearing and went on to become, under the stage name of Stevie Wonder,
one of the great pop singers and and songwriters of the seventies.*

* Paul Aurandt, PoillHorvey's The Rest of the Story (NeiV York:
Doubleday, 1977). Edited and compiled by Lynne Harvey. Copyright © by
Paulynne, Inc.

Some readers are saying right now as they read these lines: "Oh,
phooey! Flattery! Bear oil! I've tried that stuff It doesn't work -
not with intelligent people."

Of course flattery seldom works with discerning people. It is shallow,
selfish and insincere. It ought to fail and it usually does. True,
some people are so hungry, so thirsty, for appreciation that they will
swallow anything, just as a starving man will eat grass and fishworms.

Even Queen Victoria was susceptible to flattery. Prime Minister
Benjamin Disraeli confessed that he put it on thick in dealing with
the Queen. To use his exact words, he said he "spread it on with a
trowel." But Disraeli

was one of the most polished, deft and adroit men who ever ruled the
far-flung British Empire. He was a genius in his line. What would work
for him wouldn't necessarily work for you and me. In the long run,
flattery will do you more harm than good. Flattery is counterfeit, and
like counterfeit money, it will eventually get you into trouble if you
pass it to someone else.

The difference between appreciation and flattery? That is simple. One
is sincere and the other insincere. One comes from the heart out; the
other from the teeth out. One is unselfish; the other selfish. One is
universally admired; the other universally condemned.

I recently saw a bust of Mexican hero General Alvaro Obregon in the
Chapultepec palace in Mexico City. Below the bust are carved these
wise words from General Obregon's philosophy: "Don't be afraid of
enemies who attack you. Be afraid of the friends who fiatter you."

No! No! No! I am not suggesting fiattery! Far from it. I'm talking
about a new way of life. Let me repeat. I am talking about a new way
of life.

King George V had a set of six maxims displayed on the walls of his
study at Buckingham Palace. One of these maxims said: "Teach me
neither to proffer nor receive cheap praise." That's all fiattery is -
cheap praise. I once read a definition of fiattery that may be worth
repeating: "Flattery is telling the other person precisely what he
thinks about himself"

"Use what language you will," said Ralph Waldo Emerson, "you can never
say anything but what you are ."

If all we had to do was fiatter, everybody would catch on and we
should all be experts in human relations.

When we are not engaged in thinking about some definite problem, we
usually spend about 95 percent of our time thinking about ourselves.
Now, if we stop thinking about ourselves for a while and begin to
think of the other person's good points, we won't have to resort to
fiattery so cheap and false that it can be spotted almost before it is
out of the mouth.

One of the most neglected virtues of our daily existence is
appreciation, Somehow, we neglect to praise our son or daughter when
he or she brings home a good report card, and we fail to encourage our
children when they first succeed in baking a cake or building a
birdhouse.

Nothing pleases children more than this kind of parental interest and
approval.

The next time you enjoy filet mignon at the club, send word to the
chef that it was excellently prepared, and when a tired salesperson
shows you unusual courtesy, please mention it.

Every minister, lecturer and public speaker knows the discouragement
of pouring himself or herself out to an audience and not receiving a
single ripple of appreciative comment. What applies to professionals
applies doubly to workers in offices, shops and factories and our
families and friends. In our interpersonal relations we should never
forget that all our associates are human beings and hunger for
appreciation. It is the legal tender that all souls enjoy.

Try leaving a friendly trail of little sparks of gratitude on your
daily trips. You will be surprised how they will set small flames of
friendship that will be rose beacons on your next visit.

Pamela Dunham of New Fairfield, Connecticut, had

among her responsibilities on her job the supervision of

a janitor who was doing a very poor job. The other employees

would jeer at him and litter the hallways to show

him what a bad job he was doing. It was so bad, productive

time was being lost in the shop.

Without success, Pam tried various ways to motivate

this person. She noticed that occasionally he did a particularly

good piece of work. She made a point to praise

him for it in front of the other people. Each day the job

he did all around got better, and pretty soon he started

doing all his work efficiently. Now he does an excellent

job and other people give him appreciation and recognition.

Honest appreciation got results where criticism

and ridicule failed.

Hurting people not only does not change them, it is never called for.
There is an old saying that I have cut out and pasted on my mirror
where I cannot help but see it every day:

I shall pass this way but once; any good, therefore, that I can do or
any kindness that I can show to any human being, let me do it now. Let
me not defer nor neglect it, for I shall not pass this way again.

Emerson said: "Every man I meet is my superior in some way. In that, I
learn of him."

If that was true of Emerson, isn't it likely to be a thousand times
more true of you and me? Let's cease thinking of our accomplishments,
our wants. Let's try to figure out the other person's good points.
Then forget flattery. Give honest, sincere appreciation. Be "hearty in
your approbation and lavish in your praise," and people will cherish
your words and treasure them and repeat them over a lifetime - repeat
them years after you have forgotten them.

PRINCIPLE 2 Give honest and sincere appreciation.
*** 3 "HE WHO CAN DO THIS HAS THE WHOLE WORLD WITH HIM. HE WHO CANNOT WALKS A LONELY WAY"

I often went fishing up in Maine during the summer. Personally I am
very fond of strawberries and cream, but I have found that for some
strange reason, fish prefer worms. So when I went fishing, I didn't
think about what I wanted. I thought about what they wanted. I didn't
bait the hook with strawberries and cream. Rather, I dangled a worm or
a grasshopper in front of the fish and

said: "Wouldn't you like to have that?"

Why not use the same common sense when fishing for people?

That is what Lloyd George, Great Britain's Prime Minister during World
War I, did. When someone asked him how he managed to stay in power
after the other wartime leaders - Wilson, Orlando and Clemenceau - had
been forgotten, he replied that if his staying on top might be
attributed to any one thing, it would be to his having learned that it
was necessary to bait the hook to suit the fish.

Why talk about what we want? That is childish. Absurd.

Of course, you are interested in what you want.

You are eternally interested in it. But no one else is. The

rest of us are just like you: we are interested in what we

want.

So the only way cm earth to influence other people is to talk about
what they want and show them how to get it.

Remember that tomorrow when you are trying to get somebody to do
something. If, for example, you don't want your children to smoke,
don't preach at them, and don't talk about what you want; but show
them that cigarettes may keep them from making the basketball team or
winning the hundred-yard dash.

This is a good thing to remember regardless of

whether you are dealing with children or calves or chimpanzees.

For example: one day Ralph Waldo Emerson

and his son tried to get a calf into the barn. But they

made the common mistake of thinking only of what they

wanted: Emerson pushed and his son pulled. But the

calf was doing just what they were doing; he was thinking

only of what he wanted; so he stiffened his legs and

stubbornly refused to leave the pasture. The Irish housemaid

saw their predicament. She couldn't write essays

and books; but, on this occasion at least, she had more

horse sense, or calf sense, than Emerson had. She

thought of what the calf wanted; so she put her maternal

finger in the calf s mouth and let the calf suck her finger

as she gently led him into the barn.

Every act you have ever performed since the day you were born was
performed because you wanted something. How about the time you gave a
large contribution to the Red Cross? Yes, that is no exception to the
rule. You gave the Red Cross the donation because you wanted to lend a
helping hand; you wanted to do a beautiful, unselfish, divine act. "
Inasmuch as ye have done it unto one of the least of these my
brethren, ye have done it unto me."

If you hadn't wanted that feeling more than you

wanted your money, you would not have made the contribution.

Of course, you might have made the contribution

because you were ashamed to refuse or because a

customer asked you to do it. But one thing is certain. You

made the contribution because you wanted something.

Harry A, Overstreet in his illuminating book Influencing

Human Behavior said; "Action springs out of what

we fundamentally desire . . . and the best piece of advice

which can be given to would-be persuaders,

whether in business, in the home, in the school, in politics,

is: First, arouse in the other person an eager want.

He who can do this has the whole world with him. He

who cannot walks a lonely way."

Andrew Carnegie, the poverty-stricken Scotch lad who started to work
at two cents an hour and finally gave away $365 million, learned early
in life that the only way to infiuence people is to talk in terms of
what the other person wants. He attended school only four years; yet
he learned how to handle people.

To illustrate: His sister-in-law was worried sick over her two boys.
They were at Yale, and they were so busy with their own affairs that
they neglected to write home and paid no attention whatever to their
mother's frantic letters.

Then Carnegie offered to wager a hundred dollars that he could get an
answer by return mail, without even asking for it. Someone called his
bet; so he wrote his nephews a chatty letter, mentioning casually in a
post-script that he was sending each one a five-dollar bill.

He neglected, however, to enclose the money.

Back came replies by return mail thanking "Dear Uncle Andrew" for his
kind note and-you can finish the sentence yourself.

Another example of persuading comes from Stan Novak of Cleveland,
Ohio, a participant in our course. Stan came home from work one
evening to find his youngest son, Tim, kicking and screaming on the
living room fioor. He was to start kindergarten the next day and was
protesting that he would not go. Stan's normal reaction would have
been to banish the child to his room and tell him he'd just better
make up his mind to go. He had no choice. But tonight, recognizing
that this would not really help Tim start kindergarten in the best
frame of mind, Stan sat down and thought, "If I were Tim, why would I
be excited about going to kindergarten?" He and his wife made a list
of all the fun things Tim would do such as finger painting, singing
songs, making new friends. Then they put them into action. "We all
started finger-painting on the kitchen table-my wife, Lil, my other
son Bob, and myself, all having fun. Soon Tim was peeping around the
corner. Next he was begging to participate. 'Oh, no! You have to go to
kindergarten first to learn how to finger-paint.' With all the
enthusiasm I could muster I went through the list talking in terms he
could understand-telling him all the fun he would have in
kindergarten. The next morning, I thought I was the first one up. I
went downstairs and found Tim sitting sound asleep in the living room
chair. 'What are you doing here?' I asked. 'I'm waiting to go to
kindergarten. I don't want to be late.' The enthusiasm of our entire
family had aroused in Tim an eager want that no amount of discussion
or threat could have possibly accomplished."

Tomorrow you may want to persuade somebody to do something. Before you
speak, pause and ask yourself "How can I make this person want to do
it?"

That question will stop us from rushing into a situation heedlessly,
with futile chatter about our desires.

At one time I rented the grand ballroom of a certain New York hotel
for twenty nights in each season in order to hold a series of
lectures.

At the beginning of one season, I was suddenly informed that I should
have to pay almost three times as much rent as formerly. This news
reached me after the tickets had been printed and distributed and all
announcements had been made.

Naturally, I didn't want to pay the increase, but what was the use of
talking to the hotel about what I wanted? They were interested only in
what they wanted. So a couple of days later I went to see the manager.

"I was a bit shocked when I got your letter," I said, "but I don't
blame you at all. If I had been in your position, I should probably
have written a similar letter myself Your duty as the manager of the
hotel is to make all the profit possible. If you don't do that, you
will be fired and you ought to be fired. Now, let's take a piece of
paper and write down the advantages and the disadvantages that will
accrue to you, if you insist on this increase in rent."

Then I took a letterhead and ran a line through the center and headed
one column "Advantages" and the other column "Disadvantages."

I wrote down under the head "Advantages" these words: "Ballroom free."
Then I went on to say: "You will have the advantage of having the
ballroom free to rent for dances and conventions. That is a big
advantage, for affairs like that will pay you much more than you can
get for a series of lectures. If I tie your ballroom up for twenty
nights during the course of the season, it is sure to mean a loss of
some very profitable business to you.

"Now, let's 'consider the disadvantages. First, instead of increasing
your income from me, you are going to decrease it. In fact, you are
going to wipe it out because I cannot pay the rent you are asking. I
shall be forced to hold these lectures at some other place.

"There's another disadvantage to you also. These lectures attract
crowds of educated and cultured people to your hotel. That is good
advertising for you, isn't it? In fact, if you spent five thousand
dollars advertising in the

newspapers, you couldn't bring as many people to look at your hotel as
I can bring by these lectures. That is worth a lot to a hotel, isn't
it?"

As I talked, I wrote these two "disadvantages" under

the proper heading, and handed the sheet of paper to

the manager, saying: "I wish you would carefully consider

both the advantages and disadvantages that are

going to accrue to you and then give me your final decision."

I received a letter the next day, informing me that my rent would be
increased only 50 percent instead of 300 percent.

Mind you, I got this reduction without saying a word about what I
wanted. I talked all the time about what the other person wanted and
how he could get it.

Suppose I had done the human, natural thing; suppose

I had stormed into his office and said, "What do you

mean by raising my rent three hundred percent when

you know the tickets have been printed and the announcements

made? Three hundred percent! Ridiculous!

Absurd! I won't pay it!"

What would have happened then? An argument would have begun to steam
and boil and sputter - and you know how arguments end. Even if I had
convinced him that he was wrong, his pride would have made it
difficult for him to back down and give in.

Here is one of the best bits of advice ever given about the fine art
of human relationships. "If there is any one secret of success," said
Henry Ford, "it lies in the ability to get the other person's point of
view and see things from that person's angle as well as from your
own."

That is so good, I want to repeat it: "If there is any one secret of
success, it lies in the abiUty to get the other person's point of view
and see things from that person's angle as well as from your own. "

That is so simple, so obvious, that anyone ought to see the truth of
it at a glance; yet 90 percent of the people on this earth ignore it
90 percent of the time.

An example? Look at the letters that come across your desk tomorrow
morning, and you will find that most of them violate this important
canon of common sense. Take this one, a letter written by the head of
the radio department of an advertising agency with offices scattered
across the continent. This letter was sent to the managers of local
radio stations throughout the country. (I have set down, in brackets,
my reactions to each paragraph.)

Mr. John Blank,

Blankville,

Indiana

Dear Mr. Blank:

The company desires to retain its position in advertising

agency leadership in the radio field.

[Who cares what your company desires? I am worried about my own
problems. The bank is foreclosing the mortage on my house, the bugs
are destroying the hollyhocks, the stock market tumbled yesterday. I
missed the eight-fifteen this morning, I wasn't invited to the Jones's
dance last night, the doctor tells me I have high blood pressure and
neuritis and dandruff And then what happens? I come down to the office
this morning worried, open my mail and here is some little
whippersnapper off in New York yapping about what his company wants.
Bah! If he only realized what sort of impression his letter makes, he
would get out of the advertising business and start manufacturing
sheep dip.]

This agency's national advertising accounts were the bulwark of the
network. Our subsequent clearances of station time have kept us at the
top of agencies year after year.

[You are big and rich and right at the top, are you? So what? I don't
give two whoops in Hades if you are as big as General Motors and
General Electric and the General Staff of the U.S. Army all combined.
If you had as much sense as a half-witted hummingbird, you would
realize that I am interested in how big I am - not how big you are.
All this talk about your enormous success makes me feel small and
unimportant.]

We desire to service our accounts with the last word on

radio station information.

[You desire! You desire. You unmitigated ass. I'm not interested in
what you desire or what the President of the United States desires.
Let me tell you once and for all that I am interested in what I desire
- and you haven't said a word about that yet in this absurd letter of
yours .]

Willy oil, therefore, put the company on your

preferred list for weekly station information - every single detail
that will he useful to an agency in intelligently hooking time.

["Preferred list." You have your nerve! You make me feel insignificant
by your big talk about your company - nd then you ask me to put you on
a "preferred" list, and you don't even say "please" when you ask it.]

Kprompt acknowledgment of this letter, giving us your latest "doings,
" will he mutually helpful.

[You fool! You mail me a cheap form letter - a letter scattered far
and wide like the autumn leaves - and you have the gall to ask me,
when I am worried about the mortgage and the hollyhocks and my blood
pressure, to sit down and dictate a personal note acknowledging your
form letter - and you ask me to do it "promptly." What do you mean,
"promptly".? Don't you know I am just as busy as you are - or, at
least, I like to think I am. And while we are on the subject, who gave
you the lordly right to order me around? . . . You say it will be
"mutually helpful." At last, at last, you have begun to see my
viewpoint. But you are vague about how it will be to my advantage.]

Very truly yours,

John Doe

Manager Radio Department

P.S. The enclosed reprint from the Blankville Journal will he of
interest to you, and you may want to hroadcast it over your station.

[Finally, down here in the postscript, you mention something that may
help me solve one of my problems. Why didn't you begin your letter
with - but what's the

use? Any advertising man who is guilty of perpetrating such drivel as
you have sent me has something wrong with his medulla oblongata. You
don't need a letter giving our latest doings. What you need is a quart
of iodine in your thyroid gland.]

Now, if people who devote their lives to advertising and who pose as
experts in the art of influencing people to buy - if they write a
letter like that, what can we expect from the butcher and baker or the
auto mechanic?

Here is another letter, written by the superintendent of a large
freight terminal to a student of this course, Edward Vermylen. What
effect did this letter have on the man to whom it was addressed? Read
it and then I'll tell you.

A. Zerega's Sons, Inc. 28 Front St. Brooklyn, N.Y. 11201 Attention:
Mr. Edward Vermylen Gentlemen:

The operations at our outbound-rail-receiving station are handicapped
because a material percentage of the total business is delivered us in
the late afternoon. This condition results in congestion, overtime on
the part of our forces, delays to trucks, and in some cases delays to
freight. On November 10, we received from your company a lot of 510
pieces, which reached here at 4:20 P.M.

We solicit your cooperation toward overcoming the undesirable effects
arising from late receipt of freight. May we ask that, on days on
which you ship the volume which was received on the above date, effort
be made either to get the truck here earlier or to deliver us part of
the freight during the morning?

The advantage that would accrue to you under such an arrangement would
be that of more expeditious discharge of your trucks and the assurance
that your business would go forward on the date of its receipt.

Very truly yours, J B —- Supt.

After reading this letter, Mr. Vermylen, sales manager for A. Zerega's
Sons, Inc., sent it to me with the following comment:

This letter had the reverse effect from that which was intended. The
letter begins by describing the Terminal's difficulties, in which we
are not interested, generally speaking. Our cooperation is then
requested without any thought as to whether it would inconvenience us,
and then, finally, in the last paragraph, the fact is mentioned that
if we do cooperate it will mean more expeditious discharge of our
trucks with the assurance that our freight will go forward on the date
of its receipt.

In other words, that in which we are most interested is mentioned last
and the whole effect is one of raising a spirit of antagonism rather
than of cooperation.

Let's see if we can't rewrite and improve this letter. Let's not waste
any time talking about our problems. As Henry Ford admonishes, let's
"get the other person's point of view and see things from his or her
angle, as well as from our own."

Here is one way of revising the letter. It may not be the best way,
but isn't it an improvement?

Mr. Edward Vermylen % A. Zerega's Sons, Inc. 28 Front St. Brooklyn,
N.Y. 11201

Dear Mr. Vermylen:

Your company has been one of our good customers for fourteen years.
Naturally, we are very grateful for your patronage and are eager to
give you the speedy, efficient service you deserve. However, we regret
to say that it isn't possible for us to do that when your trucks bring
us a large shipment late in the afternoon, as they did on November 10.
Why? Because many other customers make late afternoon deliveries also.
Naturally, that causes congestion. That means your trucks are held up
unavoidably at the pier and sometimes even your freight is delayed.

That's bad, but it can be avoided. If you make your deliveries

at the pier in the morning when possible, your trucks will be able to
keep moving, your freight will get immediate attention, and our
workers will get home early at night to enjoy a dinner of the
delicious macaroni and noodles that you manufacture.

Regardless of when your shipments arrive, we shall always cheerfully
do all in our power to serve you promptly. You are busy. Please don't
trouble to answer this note.

Yours truly, J B , supt.

Barbara Anderson, who worked in a bank in New York, desired to move to
Phoenix, Arizona, because of the health of her son. Using the
principles she had learned in our course, she wrote the following
letter to twelve banks in Phoenix:

Dear Sir:

My ten years of bank experience should be of interest to a rapidly
growing bank like yours.

In various capacities in bank operations with the Bankers Trust
Company in New York, leading to my present assignment as Branch
Manager, I have acquired skills in all phases of banking including
depositor relations, credits, loans and administration.

I will be relocating to Phoenix in May and I am sure I can contribute
to your growth and profit. I will be in Phoenix the week of April 3
and would appreciate the opportunity to show you how I can help your
bank meet its goals.

Sincerely, Barbara L. Anderson

Do you think Mrs. Anderson received any response from that letter?
Eleven of the twelve banks invited her to be interviewed, and she had
a choice of which bank's offer to accept. Why? Mrs. Anderson did not
state what she wanted, but wrote in the letter how she could help
them, and focused on their wants, not her own.

Thousands of salespeople are pounding the pavements today, tired,
discouraged and underpaid. Why? Because they are always thinking only
of what they want. They don't realize that neither you nor I want to
buy anything. If we did, we would go out and buy it. But both of us
are eternally interested in solving our problems. And if salespeople
can show us how their services or merchandise will help us solve our
problems, they won't need to sell us. We'll buy. And customers like to
feel that they are buying - not being sold.

Yet many salespeople spend a lifetime in selling without seeing things
from the customer's angle. For example, for many years I lived in
Forest Hills, a little community of private homes in the center of
Greater New York. One day as I was rushing to the station, I chanced
to meet a real-estate operator who had bought and sold property in
that area for many years. He knew Forest Hills well, so I hurriedly
asked him whether or not my stucco house was built with metal lath or
hollow tile. He said he didn't know and told me what I already knew -
that I could find out by calling the Forest Hills Garden Association.
The following morning, I received a letter from him. Did he give me
the information I wanted? He could have gotten it in sixty seconds by
a telephone call. But he didn't. He told me again that I could get it
by telephoning, and then asked me to let him handle my insurance.

He was not interested in helping me. He was interested only in helping
himself

J. Howard Lucas of Birmingham, Alabama, tells how two salespeople from
the same company handled the same type of situation. He reported:

"Several years ago I was on the management team of a small company.
Headquartered near us was the district office of a large insurance
company. Their agents were assigned territories, and our company was
assigned to two agents, whom I shall refer to as Carl and John.

"One morning, Carl dropped by our office and casually mentioned that
his company had just introduced a new life insurance policy for
executives and thought we

might be interested later on and he would get back to us when he had
more information on it.

"The same day, John saw us on the sidewalk while returning from a
coffee break, and he shouted: 'Hey Luke, hold up, I have some great
news for you fellows.' He hurried over and very excitedly told us
about an executive life insurance policy his company had introduced
that very day. (It was the same policy that Carl had casually
mentioned.) He wanted us to have one of the first issued. He gave us a
few important facts about the coverage and ended saying, 'The policy
is so new, I'm going to have someone from the home office come out
tomorrow and explain it. Now, in the meantime, let's get the
applications signed and on the way so he can have more information to
work with.' His enthusiasm aroused in us an eager want for this policy
even though we still did not have details. When they were made
available to us, they confirmed John's initial understanding of the
policy, and he not only sold each of us a policy, but later doubled
our coverage.

"Carl could have had those sales, but he made no effort to arouse in
us any desire for the policies."

The world is full of people who are grabbing and self-seeking.

So the rare individual who unselfishly tries to

serve others has an enormous advantage. He has little

competition. Owen D. Young, a noted lawyer and one of

America's great business leaders, once said: "People

who can put themselves in the place of other people

who can understand the workings of their minds, need

never worry about what the future has in store for

them."

If out of reading this book you get just one thing - an increased
tendency to think always in terms of other people's point of view, and
see things from their angle - if you get that one thing out of this
book, it may easily prove to be one of the building blocks of your
career.

Looking at the other person's point of view and arousing in him an
eager want for something is not to be construed as manipulating that
person so that he will do something that is only for your benefit and
his detriment.

Each party should gain from the negotiation. In the letters to Mr.
Vermylen, both the sender and the receiver of the correspondence
gained by implementing what was suggested. Both the bank and Mrs.
Anderson won by her letter in that the bank obtained a valuable
employee and Mrs. Anderson a suitable job. And in the example of
John's sale of insurance to Mr. Lucas, both gained through this
transaction.

Another example in which everybody gains through this principle of
arousing an eager want comes from Michael E. Whidden of Warwick, Rhode
Island, who is a territory salesman for the Shell Oil Company. Mike
wanted to become the Number One salesperson in his district, but one
service station was holding him back. It was run by an older man who
could not be motivated to clean up his station. It was in such poor
shape that sales were declining significantly.

This manager would not listen to any of Mike's pleas to upgrade the
station. After many exhortations and heart-to-heart talks - all of
which had no impact - Mike decided to invite the manager to visit the
newest Shell station in his territory.

The manager was so impressed by the facilities at the new station that
when Mike visited him the next time, his station was cleaned up and
had recorded a sales increase. This enabled Mike to reach the Number
One spot in his district. All his talking and discussion hadn't
helped, but by arousing an eager want in the manager, by showing him
the modern station, he had accomplished his goal, and both the manager
and Mike benefited.

Most people go through college and learn to read Virgil and master the
mysteries of calculus without ever discovering how their own minds
function. For instance: I once gave a course in Effective Speaking for
the young college graduates who were entering the employ of the
Carrier Corporation, the large air-conditioner manufacturer. One of
the participants wanted to persuade the others to play basketball in
their free time, and this is about what he said: "I want you to come
out and play basketball. I like to play basketball, but the last few
times I've been to the gymnasium there haven't been enough people to
get up a game. Two or three of us got

to throwing the ball around the other night - and I got a black eye. I
wish all of you would come down tomorrow night. I want to play
basketball."

Did he talk about anything you want? You don't want to go to a
gymnasium that no one else goes to, do you? You don't care about what
he wants. You don't want to get a black eye.

Could he have shown you how to get the things you want by using the
gymnasium? Surely. More pep. Keener edge to the appetite. Clearer
brain. Fun. Games. Basketball.

To repeat Professor Overstreet's wise advice: First, arouse in the
other person an eager want He who can do this has the whole world with
him. He who cannot walks a lonely way.

One of the students in the author's training course was worried about
his little boy. The child was underweight and refused to eat properly.
His parents used the usual method. They scolded and nagged. "Mother
wants you to eat this and that." "Father wants you to grow up to be a
big man."

Did the boy pay any attention to these pleas? Just

about as much as you pay to one fleck of sand on a sandy

beach.

No one with a trace of horse sense would expect a child three years
old to react to the viewpoint of a father thirty years old. Yet that
was precisely what that father had expected. It was absurd. He finally
saw that. So he said to himself "What does that boy want? How can I
tie up what I want to what he wants?"

It was easy for the father when he starting thinking about it. His boy
had a tricycle that he loved to ride up and down the sidewalk in front
of the house in Brooklyn. A few doors down the street lived a bully -
a bigger boy who would pull the little boy off his tricycle and ride
it himself

Naturally, the little boy would run screaming to his mother, and she
would have to come out and take the

bully off the tricycle and put her little boy on again, This happened
almost every day.

What did the little boy want? It didn't take a Sherlock Holmes to
answer that one. His pride, his anger, his desire for a feeling of
importance - all the strongest emotions in his makeup - goaded him to
get revenge, to smash the bully in the nose. And when his father
explained that the boy would be able to wallop the daylights out of
the bigger kid someday if he would only eat the things his mother
wanted him to eat - when his father promised him that - there was no
longer any problem of dietetics. That boy would have eaten spinach,
sauerkraut, salt mackerel - anything in order to be big enough to whip
the bully who had humiliated him so often.

After solving that problem, the parents tackled another: the little
boy had the unholy habit of wetting his bed.

He slept with his grandmother. In the morning, his grandmother would
wake up and feel the sheet and say: "Look, Johnny, what you did again
last night."

He would say: "No, I didn't do it. You did it."

Scolding, spanking, shaming him, reiterating that the parents didn't
want him to do it - none of these things kept the bed dry. So the
parents asked: "How can we make this boy want to stop wetting his
bed?"

What were his wants? First, he wanted to wear pajamas like Daddy
instead of wearing a nightgown like Grandmother. Grandmother was
getting fed up with his nocturnal iniquities, so she gladly offered to
buy him a pair of pajamas if he would reform. Second, he wanted a bed
of his own. Grandma didn't object.

His mother took him to a department store in Brooklyn, winked at the
salesgirl, and said: "Here is a little gentleman who would like to do
some shopping."

The salesgirl made him feel important by saying: "Young man, what can
I show you?"

He stood a couple of inches taller and said: "I want to

buy a bed for myself."

When he was shown the one his mother wanted him

to buy, she winked at the salesgirl and the boy was persuaded

to buy it.

The bed was delivered the next day; and that night, when Father came
home, the little boy ran to the door shouting: "Daddy! Daddy! Come
upstairs and see my bed that I bought!"

The father, looking at the bed, obeyed Charles Schwab's injunction: he
was "hearty in his approbation and lavish in his praise."

"You are not going to wet this bed, are you?" the father said. " Oh,
no, no! I am not going to wet this bed." The boy kept his promise, for
his pride was involved. That was his bed. He and he alone had bought
it. And he was wearing pajamas now like a little man. He wanted to act
like a man. And he did.

Another father, K. T. Dutschmann, a telephone engineer, a student of
this course, couldn't get his three-year old daughter to eat breakfast
food. The usual scolding, pleading, coaxing methods had all ended in
futility. So the parents asked themselves: "How can we make her want
to do it?"

The little girl loved to imitate her mother, to feel big

and grown up; so one morning they put her on a chair

and let her make the breakfast food. At just the psychological

moment. Father drifted into the kitchen while

she was stirring the cereal and she said: "Oh, look.

Daddy, I am making the cereal this morning."

She ate two helpings of the cereal without any coaxing, because she
was interested in it. She had achieved a feeling of importance; she
had found in making the cereal an avenue of self-expression.

William Winter once remarked that "self-expression is the dominant
necessity of human nature." Why can't we adapt this same psychology to
business dealings? When we have a brilliant idea, instead of making
others think it is ours, why not let them cook and stir the idea
themselves.

They will then regard it as their own; they will like it and maybe eat
a couple of helpings of it.

Remember: "First, arouse in the other person an eager want. He who can
do this has the whole world with him. He who cannot walks a lonely
way."

PRINCIPLE 3 Arouse in the other person an eager want.
*** In a Nutshell

FUNDAMENTAL TECHNIQUES IN HANDLING PEOPLE

PRINCIPLE 1

Don't criticize, condemn or complain.

PRINCIPLE 2

Give honest and sincere appreciation.

PRINCIPLE 3

Arouse in the other person an eager want.
