part0000

How to win friends and influence people.

Includes index.

1. Success. I. Titie.

BF637.S8C37 1981 158'. 1 80-28759

ISBNO-671-42517-X

Preface to Revised Edition

How to Win Friends and Influence People was first published in 1937 in
an edition of only five thousand copies. Neither Dale Carnegie nor the
publishers, Simon and Schuster, anticipated more than this modest
sale. To their amazement, the book became an overnight sensation, and
edition after edition rolled off the presses to keep up with the
increasing public demand. Now to Win Friends and Infuence People took
its place in publishing history as one of the all-time international
best-sellers. It touched a nerve and filled a human need that was more
than a faddish phenomenon of post-Depression days, as evidenced by its
continued and uninterrupted sales into the eighties, almost half a
century later.

Dale Carnegie used to say that it was easier to make a million dollars
than to put a phrase into the English language. How to Win Friends and
Influence People became such a phrase, quoted, paraphrased, parodied,
used in innumerable contexts from political cartoon to novels. The
book itself was translated into almost every known written language.
Each generation has discovered it anew and has found it relevant.

Which brings us to the logical question: Why revise a book that has
proven and continues to prove its vigorous and universal appeal? Why
tamper with success?

To answer that, we must realize that Dale Carnegie himself was a
tireless reviser of his own work during his lifetime. How to Win
Friends and Influence People was written to be used as a textbook for
his courses in Effective Speaking and Human Relations and is still
used in those courses today. Until his death in 1955 he constantly improved
and revised the course itself to make it applicable to the evolving
needs of an every-growing public. No one was more sensitive to the
changing currents of present-day life than Dale Carnegie. He
constantly improved and refined his methods of teaching; he updated
his book on Effective Speaking several times. Had he lived longer, he
himself would have revised How to Win Friends and Influence People to
better reflect the changes that have taken place in the world since
the thirties.

Many of the names of prominent people in the book, well known at the
time of first publication, are no longer recognized by many of today's
readers. Certain examples and phrases seem as quaint and dated in our
social climate as those in a Victorian novel. The important message
and overall impact of the book is weakened to that extent.

Our purpose, therefore, in this revision is to clarify and strengthen
the book for a modern reader without tampering with the content. We
have not "changed" How to Win Friends and Influence People except to
make a few excisions and add a few more contemporary examples. The
brash, breezy Carnegie style is intact-even the thirties slang is
still there. Dale Carnegie wrote as he spoke, in an intensively
exuberant, colloquial, conversational manner.

So his voice still speaks as forcefully as ever, in the book and in
his work. Thousands of people all over the world are being trained in
Carnegie courses in increasing numbers each year. And other thousands
are reading and studying How to Win Friends and Influence People and
being inspired to use its principles to better their lives. To all of
them, we offer this revision in the spirit of the honing and polishing
of a finely made tool.

Dorothy Carnegie (Mrs. Dale Carnegie)

How This Book Was

Written-And Why

by Dale Carnegie

During the first thirty-five years of the twentieth century, the
pubhshing houses of America printed more than a fifth of a million
different books. Most of them were deadly dull, and many were
financial failures. "Many," did I say? The president of one of the
largest publishing houses in the world confessed to me that his
company, after seventy-five years of publishing experience, still lost
money on seven out of every eight books it published.

Why, then, did I have the temerity to write another book? And, after I
had written it, why should you bother to read it?

Fair questions, both; and I'll try to answer them.

I have, since 1912, been conducting educational courses for business
and professional men and women in New York. At first, I conducted
courses in public speaking only - courses designed to train adults, by
actual experience, to think on their feet and express their ideas with
more clarity, more effectiveness and more poise, both in business
interviews and before groups.

But gradually, as the seasons passed, I realized that as sorely as these adults needed training in effective speaking, they needed still more training in the fine art of getting along with people in everyday business and social contacts.

I also gradually realized that I was sorely in need of such training
myself as I look back across the years, I am appalled at my own
frequent lack of finesse and understanding. How I wish a book such as
this had been placed in my hands twenty years ago! What a priceless
boon it would have been.

Dealing with people is probably the biggest problem you face,
especially if you are in business. Yes, and that is also true if you
are a housewife, architect or engineer.

Research done a few years ago under the auspices of the Carnegie
Foundation for the Advancement of Teaching uncovered a most important
and significant fact - a fact later confirmed by additional studies
made at the Carnegie Institute of Technology. These investigations
revealed that even in such technical lines as engineering, about 15
percent of one's financial success is due to one's technical knowledge
and about 85 percent is due to skill in human engineering-to
personality and the ability to lead people.

For many years, I conducted courses each season at the Engineers' Club of Philadelphia, and also courses
for the New York Chapter of the American Institute of
Electrical Engineers. A total of probably more than fifteen
hundred engineers have passed through my
classes. They came to me because they had finally realized,
after years of observation and experience, that the
highest-paid personnel in engineering are frequently
not those who know the most about engineering. One
can for example, hire mere technical ability in engineering,
accountancy, architecture or any other profession
at nominal salaries. But the person who has
technical knowledge plus the ability to express ideas, to
assume leadership, and to arouse enthusiasm among
people-that person is headed for higher earning power.

In the heyday of his activity, John D. Rockefeller said that "the
ability to deal with people is as purchasable a commodity as sugar or
coffee." "And I will pay more for that ability," said John D., "than
for any other under the sun."

Wouldn't you suppose that every college in the land would conduct
courses to develop the highest-priced ability under the sun? But if
there is just one practical, common-sense course of that kind given
for adults in even one college in the land, it has escaped my
attention up to the present writing.

The University of Chicago and the United Y.M.C.A. Schools conducted a
survey to determine what adults want to study.

That survey cost $25,000 and took two years. The last part of the
survey was made in Meriden, Connecticut. It had been chosen as a typical American town. Every
adult in Meriden was interviewed and requested to answer
156 questions-questions such as "What is your
business or profession? Your education? How do you
spend your spare time? What is your income? Your hobbies?
Your ambitions? Your problems? What subjects are
you most interested in studying?" And so on. That survey
revealed that health is the prime interest of adults
and that their second interest is people; how to understand
and get along with people; how to make people
like you; and how to win others to your way of thinking.

So the committee conducting this survey resolved to conduct such a
course for adults in Meriden. They searched diligently for a practical
textbook on the subject and found-not one. Finally they approached one
of the world's outstanding authorities on adult education and asked
him if he knew of any book that met the needs of this group. "No," he
replied, "I know what those adults want. But the book they need has
never been written."

I knew from experience that this statement was true, for I myself had
been searching for years to discover a practical, working handbook on
human relations.

Since no such book existed, I have tried to write one for use in my
own courses. And here it is. I hope you like it.

In preparation for this book, I read everything that I could find on
the subject - everything from newspaper columns, magazine articles,
records of the family courts, the writings of the old philosophers and
the new psychologists. In addition, I hired a trained researcher to
spend one and a half years in various libraries reading everything I
had missed, plowing through erudite tomes on psychology, poring over
hundreds of magazine articles, searching through countless
biographies, trying to ascertain how the great leaders of all ages had
dealt with people. We read their biographies. We read the life stories
of all great leaders from Julius Caesar to Thomas Edison. I recall
that we read over one hundred biographies of Theodore Roosevelt alone.
We were determined to spare no time, no expense, to discover every
practical idea that anyone had ever used throughout the ages for winning friends and influencing people.

I personally interviewed scores of successful people, some of them
world-famous-inventors like Marconi and Edison; political leaders like
Franklin D. Roosevelt and James Farley; business leaders like Owen D.
Young; movie stars like Clark Gable and Mary Pickford; and explorers
like Martin Johnson and tried to discover the techniques they used in
human relations.

From all this material, I prepared a short talk. I called it "How to
Win Friends and Influence People." I say "short." It was short in the
beginning, but it soon expanded to a lecture that consumed one hour
and thirty minutes. For years, I gave this talk each season to the
adults in the Carnegie Institute courses in New York.

I gave the talk and urged the listeners to go out and test it in their
business and social contacts, and then come back to class and speak
about their experiences and the results they had achieved. What an
interesting assignment! These men and women, hungry for
self-improvement, were fascinated by the idea of working in a new kind
of laboratory - the first and only laboratory of human relationships
for adults that had ever existed.

This book wasn't written in the usual sense of the word. It grew as a
child grows. It grew and developed out of that laboratory, out of the
experiences of thousands of adults.

Years ago, we started with a set of rules printed on a card no larger
than a postcard. The next season we printed a larger card, then a
leaflet, then a series of booklets, each one expanding in size and
scope. After fifteen years of experiment and research came this book.

The rules we have set down here are not mere theories or guesswork.
They work like magic. Incredible as it sounds, I have seen the
application of these principles literally revolutionize the lives of
many people.

To illustrate: A man with 314 employees joined one of these courses.
For years, he had driven and criticized and condemned his employees
without stint or discretion. kindness, words of appreciation and
encouragement were alien to his lips. After studying the principles discussed in
this book, this employer sharply altered his philosophy of life. His
organization is now inspired with a new loyalty, a new enthusiasm, a
new spirit of teamwork. Three hundred and fourteen enemies have been
turned into 314 friends. As he proudly said in a speech before the
class: "When I used to walk through my establishment, no one greeted
me. My employees actually looked the other way when they saw me
approaching. But now they are all my friends and even the janitor
calls me by my first name."

This employer gained more profit, more leisure and what is infinitely
more important - he found far more happiness in his business and in his
home.

Countless numbers of salespeople have sharply increased their sales by
the use of these principles. Many have opened up new accounts -
accounts that they had formerly solicited in vain. Executives have
been given increased authority, increased pay. One executive reported
a large increase in salary because he applied these truths. Another,
an executive in the Philadelphia Gas Works Company, was slated for
demotion when he was sixty-five because of his belligerence, because
of his inability to lead people skillfully. This training not only
saved him from the demotion but brought him a promotion with increased
pay.

On innumerable occasions, spouses attending the banquet given at the
end of the course have told me that their homes have been much happier
since their husbands or wives started this training.

People are frequently astonished at the new results they achieve. It
all seems like magic. In some cases, in their enthusiasm, they have
telephoned me at my home on Sundays because they couldn't wait
forty-eight hours to report their achievements at the regular session
of the course.

One man was so stirred by a talk on these principles that he sat far
into the night discussing them with other members of the class. At
three o'clock in the morning, the others went home. But he was so
shaken by a realization of his own mistakes, so inspired by the vista
of a new and richer world opening before him, that he was unable to sleep.
He didn't sleep that night or the next day or the next night.

Who was he? A naive, untrained individual ready to gush over any new
theory that came along? No, Far from it. He was a sophisticated, blase
dealer in art, very much the man about town, who spoke three languages
fluently and was a graduate of two European universities.

While writing this chapter, I received a letter from a German of the
old school, an aristocrat whose forebears had served for generations
as professional army officers under the Hohenzollerns. His letter,
written from a transatlantic steamer, telling about the application of
these principles, rose almost to a religious fervor.

Another man, an old New Yorker, a Harvard graduate, a wealthy man, the
owner of a large carpet factory, declared he had learned more in
fourteen weeks through this system of training about the fine art of
infiuencing people than he had learned about the same subject during
his four years in college. Absurd? Laughable? Fantastic? Of course,
you are privileged to dismiss this statement with whatever adjective
you wish. I am merely reporting, without comment, a declaration made
by a conservative and eminently successful Harvard graduate in a
public address to approximately six hundred people at the Yale Club in
New York on the evening of Thursday, February 23, 1933.

"Compared to what we ought to be," said the famous Professor William
James of Harvard, "compared to what we ought to be, we are only half
awake. We are making use of only a small part of our physical and
mental resources. Stating the thing broadly, the human individual thus
lives far within his limits. He possesses powers of various sorts
which he habitually fails to use,"

Those powers which you "habitually fail to use"! The sole purpose of
this book is to help you discover, develop and profit by those dormant
and unused assets,

"Education," said Dr. John G. Hibben, former president of Princeton
University, "is the ability to meet life's situations,"

If by the time you have finished reading the first three chapters of
this book - if you aren't then a httle better equipped to meet life's
situations, then I shall consider this book to be a total failure so
far as you are concerned. For "the great aim of education," said
Herbert Spencer, "is not knowledge but action."

And this is an action book.

DALE CARNEGIE

1936

** Nine Suggestions on How to Get the Most Out of This Book

1. If you wish to get the most out of this book, there is one
indispensable requirement, one essential infinitely more important
than any rule or technique. Unless you have this one fundamental
requisite, a thousand rules on how to study will avail little. And if
you do have this cardinal endowment, then you can achieve wonders
without reading any suggestions for getting the most out of a book.

What is this magic requirement? Just this: a deep, driving desire to learn, a vigorous determination to increase your ability to deal with people.

How can you develop such an urge? By constantly reminding yourself how
important these principles are to you. Picture to yourself how their
mastery will aid you in leading a richer, fuller, happier and more
fulfilling life. Say to yourself over and over: "My popularity, my
happiness and sense of worth depend to no small extent upon my skill
in dealing with people."

view of it. You will probably be tempted then to rush on to the next
one. But don't - unless you are reading merely for entertainment. But
if you are reading because you want to increase your skill in human
relations, then go back and reread each chapter thoroughly. In the
long run, this will mean saving time and getting results.

3. Stop frequently in your reading to think over what you are reading.
Ask yourself just how and when you can apply each suggestion.

4. Read with a crayon, pencil, pen, magic marker or highlighter in
your hand. When you come across a suggestion that you feel you can
use, draw a line beside it.

If it is a four-star suggestion, then underscore every sentence or
highlight it, or mark it with "****". Marking and underscoring a book
makes it more interesting, and far easier to review rapidly.

5. I knew a woman who had been office manager for a large insurance
concern for fifteen years. Every month, she read all the insurance
contracts her company had issued that month. Yes, she read many of the
same contracts over month after month, year after year. Why? Because
experience had taught her that that was the only way she could keep
their provisions clearly in mind. I once spent almost two years
writing a book on public speaking and yet I found I had to keep going
back over it from time to time in order to remember what I had written
in my own book. The rapidity with which we forget is astonishing.

So, if you want to get a real, lasting benefit out of this book, don't
imagine that skimming through it once will suffice. After reading it
thoroughly, you ought to spend a few hours reviewing it every month.
Keep it on your desk in front of you every day. Glance through it
often. Keep constantly impressing yourself with the rich possibilities
for improvement that still lie in the offing. Remember that the use of
these principles can be made habitual only by a constant and vigorous
campaign of review and application. There is no other way.

6. Bernard Shaw once remarked: "If you teach a man anything, he will
never learn." Shaw was right. Learning is an active process. We learn
by doing. So, if you desire to master the principles you are studying in this book, do something
about them. Apply these rules at every opportunity. If you don't you
will forget them quickly. Only knowledge that is used sticks in your
mind.

You will probably find it difficult to apply these suggestions all the
time. I know because I wrote the book, and yet frequently I found it
difficult to apply everything I advocated. For example, when you are
displeased, it is much easier to criticize and condemn than it is to
try to understand the other person's viewpoint. It is frequently
easier to find fault than to find praise. It is more natural to talk
about what vou want than to talk about what the other person wants.
And so on. So, as you read this book, remember that you are not merely
trying to acquire information. You are attempting to form new habits.
Ah yes, you are attempting a new way of life. That will require time
and persistence and daily application.

So refer to these pages often. Regard this as a working handbook on
human relations; and whenever you are confronted with some specific
problem - such as handling a child, winning your spouse to your way of
thinking, or satisfying an irritated customer - hesitate about doing
the natural thing, the impulsive thing. This is usually wrong.
Instead, turn to these pages and review the paragraphs you have
underscored. Then try these new ways and watch them achieve magic for
you.

7. Offer your spouse, your child or some business associate a dime or
a dollar every time he or she catches you violating a certain
principle. Make a lively game out of mastering these rules.

8. The president of an important Wall Street bank once described, in a
talk before one of my classes, a highly efficient system he used for
self-improvement. This man had little formal schooling; yet he had
become one of the most important financiers in America, and he
confessed that he owed most of his success to the constant application
of his homemade system. This is what he does, I'll put it in his own words as accurately as I can remember.

"For years I have kept an engagement book showing all the appointments I had during the day. My family never made any
plans for me on Saturday night, for the family knew that I devoted a
part of each Saturday evening to the illuminating process of
self-examination and review and appraisal. After dinner I went off by
myself, opened my engagement book, and thought over all the
interviews, discussions and meetings that had taken place during the
week. I asked myself 

'What mistakes did I make that time?' 'What did I do that was
right and in what way could I have improved my performance?' 'What
lessons can I learn from that experience?'

"I often found that this weekly review made me very unhappy. I was
frequently astonished at my own blunders. Of course, as the years
passed, these blunders became less frequent. Sometimes I was inclined
to pat myself on the back a little after one of these sessions. This
system of self-analysis, self-education, continued year after year,
did more for me than any other one thing I have ever attempted.

"It helped me improve my ability to make decisions - and it aided me
enormously in all my contacts with people. I cannot recommend it too
highly."

Why not use a similar system to check up on your application of the
principles discussed in this book? If you do, two things will result.

First, you will find yourself engaged in an educational process that
is both intriguing and priceless.

Second, you will find that your ability to meet and deal with people
will grow enormously.

9. You will find at the end of this book several blank pages on which
you should record your triumphs in the application of these
principles. Be specific. Give names, dates, results. Keeping such a
record will inspire you to greater efforts; and how fascinating these
entries will be when you chance upon them some evening years from now!

In order to get the most out of this book:

a. Develop a deep, driving desire to master the principles of human
relations,

b. Read each chapter twice before going on to the next one.

c. As you read, stop frequently to ask yourself how you can apply each
suggestion.

d. Underscore each important idea.

e. Review this book each month.

f. Apply these principles at every opportunity. Use this volume as a
working handbook to help you solve your daily problems.

g. Make a lively game out of your learning by offering some friend a
dime or a dollar every time he or she catches you violating one of
these principles.

h. Check up each week on the progress you are making. Ask yourself
what mistakes you have made, what improvement, what lessons you have
learned for the future.

i. Keep notes in the back of this book showing how and when you have
applied these principles.


