* PART TWO Ways to Make People Like You
** 1 DO THIS AND YOU'LL BE WELCOME ANYWHERE

Why read this book to find out how to win fi-iends? Why not study the
technique of the greatest winner of fi'iends the world has ever known?
Who is he? You may meet him tomorrow coming down the street. When you
get within ten feet of him, he will begin to wag his tail. If you stop
and pat him, he will almost jump out of his skin to show you how much
he likes you. And you know that behind this show of affection on his
part, there are no ulterior motives: he doesn't want to sell you any
real estate, and he doesn't want to marry you.

Did you ever stop to think that a dog is the only animal that doesn't
have to work for a living? A hen has to lay eggs, a cow has to give
milk, and a canary has to sing. But a dog makes his living by giving
you nothing but love.

When I was five years old, my father bought a little yellow-haired pup
for fifty cents. He was the light and joy of my childhood. Every
afternoon about four-thirty, he would sit in the front yard with his
beautiful eyes staring steadfastly at the path, and as soon as he
heard my voice or saw me swinging my dinner pail through the buck
brush, he was off like a shot, racing breathlessly up the hill to
greet me with leaps of joy and barks of sheer ecstasy.

Tippy was my constant companion for five years. Then one tragic night -
1 shall never forget it - he was killed within ten feet of my head,
killed by lightning. Tippy's death was the tragedy of my boyhood.

You never read a book on psychology, Tippy. You didn't need to. You
knew by some divine instinct that you can make more friends in two
months by becoming genuinely interested in other people than you can
in two years by trying to get other people interested in you. Let me
repeat that. You can make more friends in two months by becoming
interested in other people than you can in two years by trying to get
other people interested in you.

Yet I know and you know people who blunder through life trying to
wigwag other people into becoming interested in them.

Of course, it doesn't work. People are not interested

in you. They are not interested in me. They are interested

in themselves - morning, noon and after dinner.

The New York Telephone Company made a detailed study of telephone
conversations to find out which word is the most frequently used. You
have guessed it: it is the personal pronoun "L" "L" L" It was used
3,900 times in 500 telephone conversations. "L" "L" "L" "L" When you
see a group photograph that you are in, whose picture do you look for
first?

If we merely try to impress people and get people interested in us, we
will never have many true, sincere friends. Friends, real friends, are
not made that way.

Napoleon tried it, and in his last meeting with Josephine

he said: "Josephine, I have been as fortunate as

any man ever was on this earth; and yet, at this hour, you

are the only person in the world on whom I can rely."

And historians doubt whether he could rely even on

her.

Alfred Adler, the famous Viennese psychologist, wrote a book entitled
What Life Should Mean to You. In that book he says: "It is the
individual who is not interested in his fellow men who has the
greatest difficulties in life and provides the greatest injury to
others. It is from among such individuals that all human failures
spring."

You may read scores of erudite tomes on psychology without coming
across a statement more significant for you and for me. Adler's
statement is so rich with meaning that I am going to repeat it in
italics:

It is the individual who is not interested in his fellow men who has
the greatest difjculties in life and provides the greutest injury to
others. It is from umong such individuals that all humun failures
spring.

I once took a course in short-story writing at New York University,
and during that course the editor of a leading magazine talked to our
class. He said he could pick up any one of the dozens of stories that
drifted across his desk every day and after reading a few paragraphs
he

could feel whether or not the author liked people. "If the author
doesn't like people," he said, "people won't like his or her stories."

This hard-boiled editor stopped twice in the course of his talk on
fiction writing and apologized for preaching a sermon. "I am telling
you," he said, "the same things your preacher would tell you, but
remember, you have to be interested in people if you want to be a
successful writer of stories."

If that is true of writing fiction, you can be sure it is true of
dealing with people face-to-face.

I spent an evening in the dressing room of

Howard

Thurston the last time he appeared on

Broadway -

Thurston was the acknowledged dean of magicians. For forty

years he had traveled all over the world, time and again,

creating illusions, mystifying audiences, and making

people gasp with astonishment. More than 60 million

people had paid admission to his show, and he had made

almost $2 million in profit.

I asked Mr. Thurston to tell me the secret of his success. His
schooling certainly had nothing to do with it, for he ran away from
home as a small boy, became a hobo, rode in boxcars, slept in
haystacks, begged his food from door to door, and learned to read by
looking out of boxcars at signs along the railway.

Did he have a superior knowledge of magic? No, he

told me hundreds of books had been written about legerdemain

and scores of people knew as much about it as

he did. But he had two things that the others didn't have.

First, he had the ability to put his personality across the

footlights. He was a master showman. He knew human

nature. Everj^thing he did, every gesture, every intonation

of his voice, every lifting of an eyebrow had been

carefully rehearsed in advance, and his actions were

timed to split seconds. But, in addition to that, Thurston

had a genuine interest in people. He told me that many

magicians would look at the audience and say to themselves,

"Well, there is a bunch of suckers out there, a

bunch of hicks; I'll fool them all right." But Thurston's

method was totally different. He told me that every time he went on
stage he said to himself "I am gratefUl because these people come to
see me, They make it possible for me to make my living in a very
agreeable way. I'm going to give them the very best I possibly can."

He declared he never stepped in front of the footlights

without first saying to himself over and over: "I love my

audience. I love my audience." Ridiculous? Absurd?

You are privileged to think anything you like. I

am

merely passing it on to you without comment as a recipe

used by one of the most famous magicians of all time.

George Dyke of North Warren, Pennsylvania, was forced to retire from
his service station business after thirty years when a new highway was
constructed over the site of his station. It wasn't long before the
idle days of retirement began to bore him, so he started filling in
his time trying to play music on his old fiddle. Soon he was traveling
the area to listen to music and talk with many of the accomplished
fiddlers. In his humble and friendly way he became generally
interested in learning the background and interests of every musician
he met. Although he was not a great fiddler himself, he made many
friends in this pursuit. He attended competitions and soon became
known to the country music fans in the eastern part of the United
States as "Uncle George, the Fiddle Scraper from Kinzua County." When
we heard Uncle George, he was seventy-two and enjoying every minute of
his life. By having a sustained interest in other people, he created a
new life for himself at a time when most people consider their
productive years over.

That, too, was one of the secrets of Theodore Roosevelt's astonishing
popularity. Even his servants loved him. His valet, James E. Amos,
wrote a book about him entitled Theodore Roosevelt, Hero to His Valet.
In that book Amos relates this illuminating incident:

My wife one time asked the President about a bobwhite. She had never
seen one and he described it to her fully. Sometime later, the
telephone at our cottage rang. [Amos and his wife lived in a little
cottage on the Roosevelt estate at Oyster Bay.] My wife answered it
and it was Mr. Roosevelt himself He had called her, he said, to tell
her that there

was a bobwhite outside her window and that if she would look out she
might see it. Little things like that were so characteristic of him.
Whenever he went by our cottage, even though we were out of sight, we
would hear him call out: "Oo-oo-oo, Annie?" or "Oo-oo-oo, James!" It
was just a friendly greeting as he went by.

How could employees keep from liking a man like that? How could anyone
keep from liking him? Roosevelt called at the White House one day when
the President and Mrs. Taft were away. His honest liking for humble
people was shown by the fact that he greeted all the old White House
servants by name, even the scullery maids.

"When he saw Alice, the kitchen maid," writes Archie Butt, "he asked
her if she still made corn bread. Alice told him that she sometimes
made it for the servants, but no one ate it upstairs.

'"They show bad taste,' Roosevelt boomed, 'and I'll tell the President
so when I see him.'

"Alice brought a piece to him on a plate, and he went

over to the office eating it as he went and greeting gardeners

and laborers as he passed. . .

"He addressed each person just as he had addressed

them in the past. Ike Hoover, who had been head usher

at the White House for forty years, said with tears in his

eyes: 'It is the only happy day we had in nearly two

years, and not one of us would exchange it for a hundred-dollar

bill.'"

The same concern for the seemingly unimportant people helped sales
representative Edward M. Sykes, Jr., of Chatham, New Jersey, retain an
account. "Many years ago," he reported, "I called on customers for
Johnson and Johnson in the Massachusetts area. One account was a drug
store in Hingham. Whenever I went into this store I would always talk
to the soda clerk and sales clerk for a few minutes before talking to
the owner to obtain his order. One day I went up to the owner of the
store, and he told me to leave as he was not interested in buying J&J
products anymore because he felt they were concentrating their
activities on food and discount stores

to the detriment of the small drugstore. I left with my tail between
my legs and drove around the town ft)r several hours. Finally, I
decided to go back and try at least to explain our position to the
owner of the store.

"When I returned I walked in and as usual said hello to the soda clerk
and sales clerk. When I walked up to the owner, he smiled at me and
welcomed me back. He then gave me double the usual order, I looked at
him with surprise and asked him what had happened since my visit only
a few hours earlier. He pointed to the young man at the soda fountain
and said that after I had left, the boy had come over and said that I
was one of the few salespeople that called on the store that even
bothered to say hello to him and to the others in the store. He told
the owner that if any salesperson deserved his business, it was I. The
owner agreed and remained a loyal customer. I never forgot that to be
genuinely interested in other people is a most important quality for a
sales-person to possess - for any person, for that matter."

I have discovered from personal experience that one

can win the attention and time and cooperation of even

the most sought-after people by becoming genuinely interested

in them. Let me illustrate.

Years ago I conducted a course in fiction writing at the Brooklyn
Institute of Arts and Sciences, and we wanted such distinguished and
busy authors as Kathleen Norris, Fannie Hurst, Ida Tarbell, Albert
Payson Terhune and Rupert Hughes to come to Brooklyn and give us the
benefit of their experiences. So we wrote them, saying we admired
their work and were deeply interested in getting their advice and
learning the secrets of their success.

Each of these letters was signed by about a hundred and fifty
students. We said we realized that these authors were busy - too busy
to prepare a lecture. So we enclosed a list of questions for them to
answer about themselves and their methods of work. They liked that.
Who wouldn't like it? So they left their homes and traveled to
Brooklyn to give us a helping hand.

By using the same method, I persuaded Leslie M. Shaw, secretary of the
treasury in Theodore Roosevelt's cabinet; George W. Wickersham,
attorney general in

Taft's cabinet; William Jennings Bryan; Franklin D. Roosevelt and many
other prominent men to come to talk to the students of my courses in
public speaking.

All of us, be we workers in a factory, clerks in an office or even a
king upon his throne - all of us like people who admire us. Take the
German Kaiser, for example. At the close of World War I he was
probably the most savagely and universally despised man on this earth.
Even his own nation turned against him when he fled over into Holland
to save his neck. The hatred against him was so intense that millions
of people would have loved to tear him limb from limb or burn him at
the stake. In the midst of all this forest fire of fury, one little
boy wrote the Kaiser a simple, sincere letter glowing with kindliness
and admiration. This little boy said that no matter what the others
thought, he would always love Wilhelm as his Emperor. The Kaiser was
deeply touched by his letter and invited the little boy to come to see
him. The boy came, so did his mother - and the Kaiser married her.
That little boy didn't need to read a book on how to win friends and
influence people. He knew how instinctively.

If we want to make friends, let's put ourselves out to do things for
other people - things that require time, energy, unselfishness and
thoughtflilness. When the Duke of Windsor was Prince of Wales, he was
scheduled to tour South America, and before he started out on that
tour he spent months studying Spanish so that he could make public
talks in the language of the country; and the South Americans loved
him for it.

For years I made it a point to find out the birthdays of my friends.
How? Although I haven't the foggiest bit of faith in astrology, I
began by asking the other party whether he believed the date of one's
birth has anything to do with character and disposition. I then asked
him or her to tell me the month and day of birth. If he or she said
November 24, for example, I kept repeating to myself, "November 24,
November 24." The minute my friend's back was turned, I wrote down the
name and birthday and later would transfer it to a birthday book. At
the beginning of each year, I had these birthday dates scheduled in my
calendar pad so that they came to my attention automatically. When the
natal day arrived, there was my letter or telegram. What a hit it
made! I

was frequently the only person on earth who remembered.

If we want to make friends, let's greet people with animation and
enthusiasm. When somebody calls you on the telephone use the same
psychology. Say "Hello" in tones that bespeak how pleased YOU are to
have the person call. Many companies train their telephone operatars
to greet all callers in a tone of voice that radiates interest and
enthusiasm. The caller feels the company is concerned about them.
Let's remember that when we answer the telephone tomorrow.

Showing a genuine interest in others not only wins friends for you,
but may develop in its customers a loyalty to your company. In an
issue of the publication of the National Bank of North America of New
York, the following letter from Madeline Rosedale, a depositor, was
published: *

Eagle, publication of the Natinnal Bank of North America, h-ew York,

March 31, 1978.

"I would like you to know how much I appreciate your staff Everyone is
so courteous, polite and helpful. What a pleasure it is, after waiting
on a long line, to have the teller greet you pleasantly.

"Last year my mother was hospitalized for five months. Frequently I
went to Marie Petrucello, a teller. She was concerned about my mother
and inquired about her progress."

Is there any doubt that Mrs. Rosedale will continue to use this bank?

Charles R. Walters, of one of the large banks in New York City, was
assigned to prepare a confidential report on a certain corporation. He
knew of only one person who possessed the facts he needed so urgently.
As Mr. Walters was ushered into the president's office, a young woman
stuck her head through a door and told the president that she didn't
have any stamps for him that day.

"I am collecting stamps for my twelve-year-old son," the president
explained to Mr. Walters.

Mr. Walters stated his mission and began asking questions.

The president was vague, general, nebulous. He

didn't want to talk, and apparently nothing could persuade

him to talk. The interview was brief and barren.

"Frankly, I didn't know what to do," Mr. Walters said as he related
the story to the class. "Then I remembered what his secretary had said
to him - stamps, twelve-year-old son. . . And I also recalled that the
foreign department of our bank collected stamps - stamps taken from
letters pouring in from every continent washed by the seven seas.

"The next afternoon I called on this man and sent in word that I had
some stamps for his boy. Was I ushered in with enthusiasm? Yes sir. He
couldn't have shaken my hand with more enthusiasm if he had been
running for Congress. He radiated smiles and good will. 'My George
will love this one,' he kept saying as he fondled the stamps. 'And
look at this! This is a treasure.'

"We spent half an hour talking stamps and looking at a picture of his
boy, and he then devoted more than an hour of his time to giving me
every bit of information I wanted - without my even suggesting that he
do it. He told me all he knew, and then called in his subordinates and
questioned them. He telephoned some of his associates. He loaded me
down with facts, figures, reports and correspondence. In the parlance
of newspaper reporters, I had a scoop."

Here is another illustration:

C. M. Knap hie, Jr., of Philadelphia had tried for years to sell fuel
to a large chain-store organization. But the chain-store company
continued to purchase its fiael from an out-of-town dealer and haul it
right past the door of Knaphle's office. Mr, Knaphle made a speech one
night before one of my classes, pouring out his hot wrath upon chain
stores, branding them as a curse to the nation.

And still he wondered why he couldn't sell them.

I suggested that he try different tactics. To put it

briefly, this is what happened. We staged a debate between

members of the course on whether the spread of

the chain store is doing the country more harm than good.

Knaphle, at my suggestion, took the negative side; he agreed to defend
the chain stores, and then went straight to an executive of the
chain-store organization that he despised and said: "I am not here to
try to sell fuel. I have come to ask you to do me a favor." He then
told about his debate and said, "I have come to you for help because I
can't think of anyone else who would be more capable of giving me the
facts I want. I'm anxious to win this debate, and I'll deeply
appreciate whatever help you can give me."

Here is the rest of the story in Mr. Knaphle's own words:

I had asked this man for precisely one minute of his time. It was with
that understanding that he consented to see me. After I had stated my
case, he motioned me to a chair and talked to me for exactly one hour
and forty-seven minutes. He called in another executive who had
written a book on chain stores. He wrote to the National Chain Store
Association and secured for me a copy of a debate on the subject. He
feels that the chain store is rendering a real service to humanity. He
is proud of what he is doing for hundreds of communities. His eyes
fairly glowed as he talked, and I must confess that he opened my eyes
to things I had never even dreamed of He changed my whole mental
attitude. As I was leaving, he walked with me to the door, put his arm
around my shoulder, wished me well in my debate, and asked me to stop
in and see him again and let him know how I made out. The last words
he said to me were: "Please see me again later in the spring. I should
like to place an order with you for fuel."

To me that was almost a miracle. Here he was offering to buy fuel
without my even suggesting it. I had made more headway in two hours by
becoming genuinely interested in him and his problems than I could
have made in ten years trying to get him interested in me and my
product.

You didn't discover a new truth, Mr. Knaphle, for a long time ago, a
hundred years before Christ was born a famous old Roman poet,
Publilius Syrus, remarked; "We are interested in others when they are
interested in us."

A show of interest, as with every other principle of human relations,
must be sincere. It must pay off not only for the person showing the
interest, but for the person receiving the attention. It is a two-way
street-both parties benefit.

Martin Ginsberg, who took our Course in Long Island New York, reported
how the special interest a nurse took in him profoundly affected his
life:

"It was Thanksgiving Day and I was ten years old. I

was in a welfare ward of a city hospital and was scheduled

to undergo major orthopedic surgery the next day.

I knew that I could only look forward to months of confinement,

convalescence and pain. My father was dead;

my mother and I lived alone in a small apartment and

we were on welfare. My mother was unable to visit me

that day.

"As the day went on, I became overwhelmed with the feeling of
loneliness, despair and fear. I knew my mother was home alone worrying
about me, not having anyone to be with, not having anyone to eat with
and not even having enough money to afford a Thanksgiving Day dinner.

"The tears welled up in my eyes, and I stuck my head under the pillow
and pulled the covers over it, I cried silently, but oh so bitterly,
so much that my body racked with pain.

"A young student nurse heard my sobbing and came over to me. She took
the covers off my face and started wiping my tears. She told me how
lonely she was, having to work that day and not being able to be with
her family. She asked me whether I would have dinner with her. She
brought two trays of food: sliced turkey, mashed a potatoes, cranberry
sauce and ice cream for dessert. She talked to me and tried to calm my
fears. Even though she was scheduled to go off duty at 4 P.M., she
stayed on her own time until almost 11 P.M. She played games with me,
talked to me and stayed with me until I finally fell asleep.

"Many Thanksgivings have come and gone since I

was ten, but one never passes without me remembering that particular
one and my feelings of frustration, fear, loneliness and the warmth
and tenderness of the stranger that somehow made it all bearable."

If you want others to like you, if you want to develop real
friendships, if you want to help others at the same time as you help
yourself, keep this principle in mind:

PRINCIPLE 1

Become genuinely interested in other people.
** 2 A SIMPLE WAY TO MAKE A GOOD FIRST IMPRESSION

At a dinner party in New York, one of the guests, a woman who had
inherited money, was eager to make a pleasing impression on everyone.
She had squandered a modest fortune on sables, diamonds and pearls.
But she hadn't done anything whatever about her face. It radiated
sourness and selfishness. She didn't realize what everyone knows:
namely, that the expression one wears on one's face is far more
important than the clothes one wears on one's back.

Charles Schwab told me his smile had been worth a

million dollars. And he was probably understating the

truth. For Schwab's personality, his charm, his ability to

make people like him, were almost wholly responsible

for his extraordinary success; and one of the most delightful

factors in his personality was his captivating

smile.

Actions speak louder than words, and a smile says, "I like you. You
make me happy. I am glad to see you." That is why dogs make such a
hit. They are so glad to

see us that they almost jump out of their skins. So, naturally, we are
glad to see them.

A baby's smile has the same effect.

Have you ever been in a doctor's waiting room and looked around at all
the glum faces waiting impatiently to be seen? Dr, Stephen K. Sproul,
a veterinarian in Raytown, Missouri, told of a typical spring day when
his waiting room was full of clients waiting to have their pets
inoculated. No one was talking to anyone else, and all were probably
thinking of a dozen other things they would rather be doing than
"wasting time" sitting in that office. He told one of our classes:
"There were six or seven clients waiting when a young woman came in
with a nine-month-old baby and a kitten. As luck would have it, she
sat down next to a gentleman who was more than a little distraught
about the long wait for service. The next thing he knew, the baby just
looked up at him with that great big smile that is so characteristic
of babies. What did that gentleman do? Just what you and I would do,
of course; he-smiled back at the baby. Soon he struck up a
conversation with the woman about her baby and his grandchildren, and
soon the entire reception room joined in, and the boredom and tension
were converted into a pleasant and enjoyable experience."

An insincere grin? No. That doesn't fool anybody. We know it is
mechanical and we resent it. I am talking about a real smile, a
heartwarming smile, a smile that comes from within, the kind of smile
that will bring a good price in the marketplace.

Professor James V. McConnell, a psychologist at the University of
Michigan, expressed his feelings about a smile. "People who smile," he
said, "tend to manage teach and sell more effectively, and to raise
happier children. There's far more information in a smile than a
frown. That's why encouragement is a much more effective teaching
device than punishment."

The employment manager of a large New York department store told me
she would rather hire a sales clerk who hadn't finished grade school,
if he or she has a pleasant smile, than to hire a doctor of philosophy
with a somber face.

The effect of a smile is powerful - even when it is unseen. Telephone
companies throughout the United States have a program called "phone
power" which is offered to employees who use the telephone for selling
their services or products. In this program they suggest that you
smile when talking on the phone. Your "smile" comes through in your
voice.

Robert Cryer, manager of a computer department for a Cincinnati, Ohio,
company, told how he had successfully found the right applicant for a
hard-to-fill position:

"I was desperately trying to recruit a Ph.D. in computer

science for my department. I finally located a

young man with ideal qualifications who was about to

be graduated from Purdue University. After several

phone conversations I learned that he had several offers

from other companies, many of them larger and better

known than mine. I was delighted when he accepted my

offer. After he started on the job, I asked him why he

had chosen us over the others. He paused for a moment

and then he said: 'I think it was because managers in the

other companies spoke on the phone in a cold, business-like

manner, which made me feel like just another business

transaction. Your voice sounded as if you were glad

to hear from me . . . that you really wanted me to be part

of your organization. ' You can be assured, I am still answering

my phone with a smile."

The chairman of the board of directors of one of the largest rubber
companies 'in the United States told me that, according to his
observations, people rarely succeed at anything unless they have fun
doing it. This industrial leader doesn't put much faith in the old
adage that hard work alone is the magic key that will unlock the door
to our desires, "I have known people," he said, "who succeeded because
they had a rip-roaring good time conducting their business. Later, I
saw those people change as the flm became work. The business had grown
dull. They lost all joy in it, and they failed."

You must have a good time meeting people if you expect them to have a
good time meeting you.

I have asked thousands of business people to smile at

someone every hour of the day for a week and then come to class and
talk about the results. How did it work? Let's see. . . Here is a
letter from William B. Steinhardt, a New York stockbroker. His case
isn't isolated. In fact, it is typical of hundreds of cases.

"1 have been married for over eighteen years," wrote Mr. Steinhardt,
"and in all that time I seldom smiled at my wife or spoke two dozen
words to her from the time I got up until I was ready to leave for
business. I was one of the worst grouches who ever walked down
Broadway.

"When you asked me to make a talk about my experience with smiles, I
thought I would try it for a week. So the next morning, while combing
my hair, I looked at my glum mug in the mirror and said to myself,
'Bill, you are going to wipe the scowl off that sour puss of yours
today. You are going to smile. And you are going to begin right now.'
As I sat down to breakfast, I greeted my wife with a 'Good morning, my
dear,' and smiled as I said it.

"You warned me that she might be surprised. Well, you underestimated
her reaction. She was bewildered. She was shocked. I told her that in
the future she could expect this as a regular occurrence, and I kept
it up every morning.

"This changed attitude of mine brought more happiness into our home in
the two months since I started than there was during the last year.

"As I leave for my office, I greet the elevator operator in the
apartment house with a 'Good morning' and a smile, I greet the doorman
with a smile. I smile at the cashier in the subway booth when I ask
for change. As I stand on the floor of the Stock Exchange, I smile at
people who until recently never saw me smile.

"I soon found that everybody was smiling back at me,

I treat those who come to me with complaints or grievances

in a cheerful manner, I smile as I listen to them

and I find that adjustments are accomplished much easier.

I find that smiles are bringing me dollars, many dollars

every day.

"I share my office with another broker. One of his clerks is a hkable
young chap, and I was so elated about the results I was getting that I
told him recently about my new philosophy of human relations. He then
confessed that when I first came to share my office with his firm he
thought me a terrible grouch - and only recently changed his mind. He
said I was really human when I smiled.

"I have also eliminated criticism from my system. I give appreciation
and praise now instead of condemnation. I have stopped talking about
what I want. I am now trying to see the other person's viewpoint. And
these things have literally revolutionized my life. I am a totally
different man, a happier man, a richer man, richer in friendships and
happiness - the only things that matter much after all."

You don't feel like smiling? Then what? Two things. First, force
yourself to smile. If you are alone, force yourself to whistle or hum
a tune or sing. Act as if you were already happy, and that will tend
to make you happy. Here is the way the psychologist and philosopher
William James put it:

"Action seems to follow feeling, but really action and feeling go
together; and by regulating the action, which is under the more direct
control of the will, we can indirectly regulate the feeling, which is
not.

"Thus the sovereign voluntary path to cheerftilness, if our
cheerfulness be lost, is to sit up cheerfully and to act and speak as
if cheerfulness were already there. . . ."

Every body in the world is seeking happiness - and there is one sure
way to find it. That is by controlling your thoughts. Happiness
doesn't depend on outward conditions. It depends on inner conditions.

It isn't what you have or who you are or where you are or what you are
doing that makes you happy or unhappy. It is what you think about it.
For example, two people may be in the same place, doing the same
thing; both may have about an equal amount of money and prestige - and
yet one may be miserable and the other happy. Why? Because of a
different mental attitude. I have seen

just as many happy faces among the poor peasants toiling with their
primitive tools in the devastating heat of the tropics as I have seen
in air-conditioned offices in New York, Chicago or Los Angeles.

"There is nothing either good or bad," said Shakespeare, "but thinking
makes it so."

Abe Lincoln once remarked that "most folks are about as happy as they
make up their minds to be." He was right. I saw a vivid illustration
of that truth as I was walking up the stairs of the Long Island
Railroad station in New York. Directly in front of me thirty or forty
crippled boys on canes and crutches were struggling up the stairs. One
boy had to be carried up. I was astonished at their laughter and
gaiety. I spoke about it to one of the men in charge of the boys. "Oh,
yes," he said, "when a boy realizes that he is going to be a cripple
for life, he is shocked at first; but after he gets over the shock, he
usually resigns himself to his fate and then becomes as happy as
normal boys."

I felt like taking my hat off to those boys. They taught me a lesson I
hope I shall never forget.

Working all by oneself in a closed-off room in an office not only is
lonely, but it denies one the opportunity of making friends with other
employees in the company. Senora Maria Gonzalez of Guadalajara,
Mexico, had such a job. She envied the shared comradeship of other
people in the company as she heard their chatter and laughter. As she
passed them in the hall during the first weeks of her employment, she
shyly looked the other way.

After a few weeks, she said to herself, "Maria, you can't expect those
women to come to you. You have to go out and meet them. " The next
time she walked to the water cooler, she put on her brightest smile
and said, "Hi, how are you today" to each of the people she met. The
effect was immediate. Smiles and hellos were returned, the hallway
seemed brighter, the job friendlier.

Acquaintanceships developed and some ripened into friendships. Her job
and her life became more pleasant and interesting.

Peruse this bit of sage advice from the essayist and publisher Elbert
Hubbard - but remember, perusing it won't do you any good unless you
apply it:

Whenever you go out-of-doors, draw the chin in, carry the crown of the
head high, and fill the lungs to the utmost; drink in the sunshine;
greet your friends with a smile, and put soul into every handclasp. Do
not fear being misunderstood and do not waste a minute thinking about
your enemies. Try to fix firmly in your mind what you would like to
do; and then, without veering off direction, you will move straight to
the goal. Keep your mind on the great and splendid things you would
like to do, and then, as the days go gliding away, you will find
yourself unconsciously seizing upon the opportunities that are
required for the fulfillment of your desire, just as the coral insect
takes from the running tide the element it needs. Picture in your mind
the able, earnest, useful person you desire to be, and the thought you
hold is hourly transforming you into that particular individual. . . .
Thought is supreme. Preserve a right mental attitude -the attitude of
courage, frankness, and good cheer. To think rightly is to create. All
things come through desire and every sincere prayer is answered. We
become like that on which our hearts are fixed. Carry your chin in and
the crown of your head high. We are gods in the chrysalis.

The ancient Chinese were a wise lot - wise in the ways of the world;
and they had a proverb that you and I ought to cut out and paste
inside our hats. It goes like this: "A man without a smiling face must
not open a shop."

Your smile is a messenger of your good will. Your smile brightens the
lives of all who see it. To someone who has seen a dozen people frown,
scowl or turn their faces away, your smile is like the sun breaking
through the clouds. Especially when that someone is under pressure
from his bosses, his customers, his teachers or parents or children, a
smile can help him realize that all is not hopeless - that there is
joy in the world.

Some years ago, a department store in New York City, in recognition of
the pressures its sales clerks were under during the Christmas rush,
presented the readers of its advertisements with the following homely
philosophy:

THE VALUE OF A SMILE AT CHRISTMAS

It costs nothing, but creates much.

It enriches those who receive, without impoverishing those

who give. It happens in a flash and the memory of it sometimes lasts

forever. None are so rich they can get along without it, and none so

poor but are richer for its benefits. It creates happiness in the
home, fosters good will in a

business, and is the countersign of friends. It is rest to the weary,
daylight to the discouraged, sunshine

to the sad, and Nature's best antidote fee trouble. Yet it cannot be
bought, begged, borrowed, or stolen, for it

is something that is no earthly good to anybody till it is

given away. And if in the last-minute rush of Christmas buying some of

our salespeople should be too tired to give you a smile,

may we ask you to leave one of yours? For nobody needs a smile so much
as those who have none

left to give!

PRINCIPLE 2 Smile.
** 3 IF YOU DON'T DO THIS, YOU ARE HEADED FOR TROUBLE

Back in 1898, a tragic thing happened in Rockland County, New York. A
child had died, and on this particular day the neighbors were
preparing to go to the funeral.

Jim Farley went out to the barn to hitch up his

horse. The ground was covered with snow, the air was

cold and snappy; the horse hadn't been exercised for days; and as he
was led out to the watering trough, he wheeled playfully, kicked both
his heels high in the air, and killed Jim Farley. So the little
village of Stony Point had two funerals that week instead of one.

Jim Farley left behind him a widow and three boys, and a few hundred
dollars in insurance.

His oldest boy, Jim, was ten, and he went to work in a

brickyard, wheeling sand and pouring it into the molds

and turning the brick on edge to be dried by the sun.

This boy Jim never had a chance to get much education.

But with his natural geniality, he had a flair for making

people like him, so he went into politics, and as the

years went by, he developed an uncanny ability for remembering

people's names.

He never saw the inside of a high school; but before he was forty-six
years of age, four colleges had honored him with degrees and he had
become chairman of the Democratic National Committee and Postmaster
General of the United States.

I once interviewed Jim Farley and asked him the secret of his success.
He said, "Hard work," and I said, "Don't be fiinny."

He then asked me what I thought was the reason for his success. I
replied: "I understand you can call ten thousand people by their first
names."

"No. You are wrong, " he said. "I can call fifty thousand people by
their first names."

Make no mistake about it. That ability helped Mr. Farley put Franklin
D. Roosevelt in the White House when he managed Roosevelt's campaign
in 1932.

During the years that Jim Farley traveled as a salesman for a gypsum
concern, and during the years that he held office as town clerk in
Stony Point, he built up a system for remembering names.

In the beginning, it was a very simple one. Whenever

he met a new acquaintance, he found out his or her complete

name and some facts about his or her family, business and pohtical
opinions. He fixed all these facts well in mind as part of the
picture, and the next time he met that person, even if it was a year
later, he was able to shake hands, inquire after the family, and ask
about the hollyhocks in the backyard. No wonder he developed a
following!

For months before Roosevelt's campaign for President began, Jim Farley
wrote hundreds of letters a day to people all over the western and
northwestern states. Then he hopped onto a train and in nineteen days
covered twenty states and twelve thousand miles, traveling by buggy,
train, automobile and boat. He would drop into town, meet his people
at lunch or breakfast, tea or dinner, and give them a "heart-to-heart
talk." Then he'd dash off again on another leg of his journey.

As soon as he arrived back East, he wrote to one person in each town
he had visited, asking for a list of all the guests to whom he had
talked. The final list contained thousands and thousands of names; yet
each person on that list was paid the subtle fiattery of getting a
personal letter from James Farley. These letters began "Dear Bill" or
"Dear Jane," and they were always signed "Jim."

Jim Farley discovered early in life that the average person is more
interested in his or her own name than in all the other names on earth
put together. Remember that name and call it easily, and you have paid
a subtle and very effective compliment. But forget it or misspell it -
and you have placed yourself at a sharp disadvantage. For example, I
once organized a public-speaking course in Paris and sent form letters
to all the American residents in the city. French typists with
apparently little knowledge of English filled in the names and
naturally they made blunders. One man, the manager of a large American
bank in Paris, wrote me a scathing rebuke because his name had been
misspelled.

Sometimes it is difficult to remember a name, particularly if it is
hard to pronounce. Rather than even try to learn it, many people
ignore it or call the person by an easy nickname. Sid Levy called on a
customer for some time whose name was Nicodemus Papadoulos. Most

people just called him "Nick." Levy told us: "I made a special effort
to say his name over several times to myself before I made my call.
When I greeted him by his full name: 'Good afternoon, Mr. Nicodemus
Papadoulos,' he was shocked. For what seemed like several minutes
there was no reply from him at all. Finally, he said with tears
rolling down his cheeks, 'Mr. Levy, in all the fifteen years I have
been in this country, nobody has ever made the effort to call me by my
right name.' "

What was the reason for Andrew Carnegie's success?

He was called the Steel King; yet he himself knew little about the
manufacture of steel. He had hundreds of people working for him who
knew far more about steel than he did.

But he knew how to handle people, and that is what

made him rich. Early in life, he showed a flair for organization,

a genius for leadership. By the time he was ten,

he too had discovered the astounding importance people

place on their own name. And he used that discovery to

win cooperation. To illustrate: When he was a boy back

in Scotland, he got hold of a rabbit, a mother rabbit.

Presto! He soon had a whole nest of little rabbits - and

nothing to feed them. But he had a brilliant idea. He told

the boys and girls in the neighborhood that if they would

go out and pull enough clover and dandelions to feed

the rabbits, he would name the bunnies in their honor.

The plan worked like magic, and Carnegie never forgot it.
