part0000

How to win friends and influence people.

Includes index.

1. Success. I. Titie.

BF637.S8C37 1981 158'. 1 80-28759

ISBNO-671-42517-X

Preface to Revised Edition

How to Win Friends and Influence People was first published in 1937 in
an edition of only five thousand copies. Neither Dale Carnegie nor the
publishers, Simon and Schuster, anticipated more than this modest
sale. To their amazement, the book became an overnight sensation, and
edition after edition rolled off the presses to keep up with the
increasing public demand. Now to Win Friends and Infuence People took
its place in publishing history as one of the all-time international
best-sellers. It touched a nerve and filled a human need that was more
than a faddish phenomenon of post-Depression days, as evidenced by its
continued and uninterrupted sales into the eighties, almost half a
century later.

Dale Carnegie used to say that it was easier to make a million dollars
than to put a phrase into the English language. How to Win Friends and
Influence People became such a phrase, quoted, paraphrased, parodied,
used in innumerable contexts from political cartoon to novels. The
book itself was translated into almost every known written language.
Each generation has discovered it anew and has found it relevant.

Which brings us to the logical question: Why revise a book that has
proven and continues to prove its vigorous and universal appeal? Why
tamper with success?

To answer that, we must realize that Dale Carnegie himself was a
tireless reviser of his own work during his lifetime. How to Win
Friends and Influence People was written to be used as a textbook for
his courses in Effective Speaking and Human Relations and is still
used in those courses today. Until his death in 1955 he constantly improved
and revised the course itself to make it applicable to the evolving
needs of an every-growing public. No one was more sensitive to the
changing currents of present-day life than Dale Carnegie. He
constantly improved and refined his methods of teaching; he updated
his book on Effective Speaking several times. Had he lived longer, he
himself would have revised How to Win Friends and Influence People to
better reflect the changes that have taken place in the world since
the thirties.

Many of the names of prominent people in the book, well known at the
time of first publication, are no longer recognized by many of today's
readers. Certain examples and phrases seem as quaint and dated in our
social climate as those in a Victorian novel. The important message
and overall impact of the book is weakened to that extent.

Our purpose, therefore, in this revision is to clarify and strengthen
the book for a modern reader without tampering with the content. We
have not "changed" How to Win Friends and Influence People except to
make a few excisions and add a few more contemporary examples. The
brash, breezy Carnegie style is intact-even the thirties slang is
still there. Dale Carnegie wrote as he spoke, in an intensively
exuberant, colloquial, conversational manner.

So his voice still speaks as forcefully as ever, in the book and in
his work. Thousands of people all over the world are being trained in
Carnegie courses in increasing numbers each year. And other thousands
are reading and studying How to Win Friends and Influence People and
being inspired to use its principles to better their lives. To all of
them, we offer this revision in the spirit of the honing and polishing
of a finely made tool.

Dorothy Carnegie (Mrs. Dale Carnegie)

How This Book Was

Written-And Why

by Dale Carnegie

During the first thirty-five years of the twentieth century, the
pubhshing houses of America printed more than a fifth of a million
different books. Most of them were deadly dull, and many were
financial failures. "Many," did I say? The president of one of the
largest publishing houses in the world confessed to me that his
company, after seventy-five years of publishing experience, still lost
money on seven out of every eight books it published.

Why, then, did I have the temerity to write another book? And, after I
had written it, why should you bother to read it?

Fair questions, both; and I'll try to answer them.

I have, since 1912, been conducting educational courses for business
and professional men and women in New York. At first, I conducted
courses in public speaking only - courses designed to train adults, by
actual experience, to think on their feet and express their ideas with
more clarity, more effectiveness and more poise, both in business
interviews and before groups.

But gradually, as the seasons passed, I realized that as sorely as these adults needed training in effective speaking, they needed still more training in the fine art of getting along with people in everyday business and social contacts.

I also gradually realized that I was sorely in need of such training
myself as I look back across the years, I am appalled at my own
frequent lack of finesse and understanding. How I wish a book such as
this had been placed in my hands twenty years ago! What a priceless
boon it would have been.

Dealing with people is probably the biggest problem you face,
especially if you are in business. Yes, and that is also true if you
are a housewife, architect or engineer.

Research done a few years ago under the auspices of the Carnegie
Foundation for the Advancement of Teaching uncovered a most important
and significant fact - a fact later confirmed by additional studies
made at the Carnegie Institute of Technology. These investigations
revealed that even in such technical lines as engineering, about 15
percent of one's financial success is due to one's technical knowledge
and about 85 percent is due to skill in human engineering-to
personality and the ability to lead people.

For many years, I conducted courses each season at the Engineers' Club of Philadelphia, and also courses
for the New York Chapter of the American Institute of
Electrical Engineers. A total of probably more than fifteen
hundred engineers have passed through my
classes. They came to me because they had finally realized,
after years of observation and experience, that the
highest-paid personnel in engineering are frequently
not those who know the most about engineering. One
can for example, hire mere technical ability in engineering,
accountancy, architecture or any other profession
at nominal salaries. But the person who has
technical knowledge plus the ability to express ideas, to
assume leadership, and to arouse enthusiasm among
people-that person is headed for higher earning power.

In the heyday of his activity, John D. Rockefeller said that "the
ability to deal with people is as purchasable a commodity as sugar or
coffee." "And I will pay more for that ability," said John D., "than
for any other under the sun."

Wouldn't you suppose that every college in the land would conduct
courses to develop the highest-priced ability under the sun? But if
there is just one practical, common-sense course of that kind given
for adults in even one college in the land, it has escaped my
attention up to the present writing.

The University of Chicago and the United Y.M.C.A. Schools conducted a
survey to determine what adults want to study.

That survey cost $25,000 and took two years. The last part of the
survey was made in Meriden, Connecticut. It had been chosen as a typical American town. Every
adult in Meriden was interviewed and requested to answer
156 questions-questions such as "What is your
business or profession? Your education? How do you
spend your spare time? What is your income? Your hobbies?
Your ambitions? Your problems? What subjects are
you most interested in studying?" And so on. That survey
revealed that health is the prime interest of adults
and that their second interest is people; how to understand
and get along with people; how to make people
like you; and how to win others to your way of thinking.

So the committee conducting this survey resolved to conduct such a
course for adults in Meriden. They searched diligently for a practical
textbook on the subject and found-not one. Finally they approached one
of the world's outstanding authorities on adult education and asked
him if he knew of any book that met the needs of this group. "No," he
replied, "I know what those adults want. But the book they need has
never been written."

I knew from experience that this statement was true, for I myself had
been searching for years to discover a practical, working handbook on
human relations.

Since no such book existed, I have tried to write one for use in my
own courses. And here it is. I hope you like it.

In preparation for this book, I read everything that I could find on
the subject - everything from newspaper columns, magazine articles,
records of the family courts, the writings of the old philosophers and
the new psychologists. In addition, I hired a trained researcher to
spend one and a half years in various libraries reading everything I
had missed, plowing through erudite tomes on psychology, poring over
hundreds of magazine articles, searching through countless
biographies, trying to ascertain how the great leaders of all ages had
dealt with people. We read their biographies. We read the life stories
of all great leaders from Julius Caesar to Thomas Edison. I recall
that we read over one hundred biographies of Theodore Roosevelt alone.
We were determined to spare no time, no expense, to discover every
practical idea that anyone had ever used throughout the ages for winning friends and influencing people.

I personally interviewed scores of successful people, some of them
world-famous-inventors like Marconi and Edison; political leaders like
Franklin D. Roosevelt and James Farley; business leaders like Owen D.
Young; movie stars like Clark Gable and Mary Pickford; and explorers
like Martin Johnson and tried to discover the techniques they used in
human relations.

From all this material, I prepared a short talk. I called it "How to
Win Friends and Influence People." I say "short." It was short in the
beginning, but it soon expanded to a lecture that consumed one hour
and thirty minutes. For years, I gave this talk each season to the
adults in the Carnegie Institute courses in New York.

I gave the talk and urged the listeners to go out and test it in their
business and social contacts, and then come back to class and speak
about their experiences and the results they had achieved. What an
interesting assignment! These men and women, hungry for
self-improvement, were fascinated by the idea of working in a new kind
of laboratory - the first and only laboratory of human relationships
for adults that had ever existed.

This book wasn't written in the usual sense of the word. It grew as a
child grows. It grew and developed out of that laboratory, out of the
experiences of thousands of adults.

Years ago, we started with a set of rules printed on a card no larger
than a postcard. The next season we printed a larger card, then a
leaflet, then a series of booklets, each one expanding in size and
scope. After fifteen years of experiment and research came this book.

The rules we have set down here are not mere theories or guesswork.
They work like magic. Incredible as it sounds, I have seen the
application of these principles literally revolutionize the lives of
many people.

To illustrate: A man with 314 employees joined one of these courses.
For years, he had driven and criticized and condemned his employees
without stint or discretion. kindness, words of appreciation and
encouragement were alien to his lips. After studying the principles discussed in
this book, this employer sharply altered his philosophy of life. His
organization is now inspired with a new loyalty, a new enthusiasm, a
new spirit of teamwork. Three hundred and fourteen enemies have been
turned into 314 friends. As he proudly said in a speech before the
class: "When I used to walk through my establishment, no one greeted
me. My employees actually looked the other way when they saw me
approaching. But now they are all my friends and even the janitor
calls me by my first name."

This employer gained more profit, more leisure and what is infinitely
more important - he found far more happiness in his business and in his
home.

Countless numbers of salespeople have sharply increased their sales by
the use of these principles. Many have opened up new accounts -
accounts that they had formerly solicited in vain. Executives have
been given increased authority, increased pay. One executive reported
a large increase in salary because he applied these truths. Another,
an executive in the Philadelphia Gas Works Company, was slated for
demotion when he was sixty-five because of his belligerence, because
of his inability to lead people skillfully. This training not only
saved him from the demotion but brought him a promotion with increased
pay.

On innumerable occasions, spouses attending the banquet given at the
end of the course have told me that their homes have been much happier
since their husbands or wives started this training.

People are frequently astonished at the new results they achieve. It
all seems like magic. In some cases, in their enthusiasm, they have
telephoned me at my home on Sundays because they couldn't wait
forty-eight hours to report their achievements at the regular session
of the course.

One man was so stirred by a talk on these principles that he sat far
into the night discussing them with other members of the class. At
three o'clock in the morning, the others went home. But he was so
shaken by a realization of his own mistakes, so inspired by the vista
of a new and richer world opening before him, that he was unable to sleep.
He didn't sleep that night or the next day or the next night.

Who was he? A naive, untrained individual ready to gush over any new
theory that came along? No, Far from it. He was a sophisticated, blase
dealer in art, very much the man about town, who spoke three languages
fluently and was a graduate of two European universities.

While writing this chapter, I received a letter from a German of the
old school, an aristocrat whose forebears had served for generations
as professional army officers under the Hohenzollerns. His letter,
written from a transatlantic steamer, telling about the application of
these principles, rose almost to a religious fervor.

Another man, an old New Yorker, a Harvard graduate, a wealthy man, the
owner of a large carpet factory, declared he had learned more in
fourteen weeks through this system of training about the fine art of
infiuencing people than he had learned about the same subject during
his four years in college. Absurd? Laughable? Fantastic? Of course,
you are privileged to dismiss this statement with whatever adjective
you wish. I am merely reporting, without comment, a declaration made
by a conservative and eminently successful Harvard graduate in a
public address to approximately six hundred people at the Yale Club in
New York on the evening of Thursday, February 23, 1933.

"Compared to what we ought to be," said the famous Professor William
James of Harvard, "compared to what we ought to be, we are only half
awake. We are making use of only a small part of our physical and
mental resources. Stating the thing broadly, the human individual thus
lives far within his limits. He possesses powers of various sorts
which he habitually fails to use,"

Those powers which you "habitually fail to use"! The sole purpose of
this book is to help you discover, develop and profit by those dormant
and unused assets,

"Education," said Dr. John G. Hibben, former president of Princeton
University, "is the ability to meet life's situations,"

If by the time you have finished reading the first three chapters of
this book - if you aren't then a httle better equipped to meet life's
situations, then I shall consider this book to be a total failure so
far as you are concerned. For "the great aim of education," said
Herbert Spencer, "is not knowledge but action."

And this is an action book.

DALE CARNEGIE

1936

** Nine Suggestions on How to Get the Most Out of This Book

1. If you wish to get the most out of this book, there is one
indispensable requirement, one essential infinitely more important
than any rule or technique. Unless you have this one fundamental
requisite, a thousand rules on how to study will avail little. And if
you do have this cardinal endowment, then you can achieve wonders
without reading any suggestions for getting the most out of a book.

What is this magic requirement? Just this: a deep, driving desire to learn, a vigorous determination to increase your ability to deal with people.

How can you develop such an urge? By constantly reminding yourself how
important these principles are to you. Picture to yourself how their
mastery will aid you in leading a richer, fuller, happier and more
fulfilling life. Say to yourself over and over: "My popularity, my
happiness and sense of worth depend to no small extent upon my skill
in dealing with people."

view of it. You will probably be tempted then to rush on to the next
one. But don't - unless you are reading merely for entertainment. But
if you are reading because you want to increase your skill in human
relations, then go back and reread each chapter thoroughly. In the
long run, this will mean saving time and getting results.

3. Stop frequently in your reading to think over what you are reading.
Ask yourself just how and when you can apply each suggestion.

4. Read with a crayon, pencil, pen, magic marker or highlighter in
your hand. When you come across a suggestion that you feel you can
use, draw a line beside it.

If it is a four-star suggestion, then underscore every sentence or
highlight it, or mark it with "****". Marking and underscoring a book
makes it more interesting, and far easier to review rapidly.

5. I knew a woman who had been office manager for a large insurance
concern for fifteen years. Every month, she read all the insurance
contracts her company had issued that month. Yes, she read many of the
same contracts over month after month, year after year. Why? Because
experience had taught her that that was the only way she could keep
their provisions clearly in mind. I once spent almost two years
writing a book on public speaking and yet I found I had to keep going
back over it from time to time in order to remember what I had written
in my own book. The rapidity with which we forget is astonishing.

So, if you want to get a real, lasting benefit out of this book, don't
imagine that skimming through it once will suffice. After reading it
thoroughly, you ought to spend a few hours reviewing it every month.
Keep it on your desk in front of you every day. Glance through it
often. Keep constantly impressing yourself with the rich possibilities
for improvement that still lie in the offing. Remember that the use of
these principles can be made habitual only by a constant and vigorous
campaign of review and application. There is no other way.

6. Bernard Shaw once remarked: "If you teach a man anything, he will
never learn." Shaw was right. Learning is an active process. We learn
by doing. So, if you desire to master the principles you are studying in this book, do something
about them. Apply these rules at every opportunity. If you don't you
will forget them quickly. Only knowledge that is used sticks in your
mind.

You will probably find it difficult to apply these suggestions all the
time. I know because I wrote the book, and yet frequently I found it
difficult to apply everything I advocated. For example, when you are
displeased, it is much easier to criticize and condemn than it is to
try to understand the other person's viewpoint. It is frequently
easier to find fault than to find praise. It is more natural to talk
about what vou want than to talk about what the other person wants.
And so on. So, as you read this book, remember that you are not merely
trying to acquire information. You are attempting to form new habits.
Ah yes, you are attempting a new way of life. That will require time
and persistence and daily application.

So refer to these pages often. Regard this as a working handbook on
human relations; and whenever you are confronted with some specific
problem - such as handling a child, winning your spouse to your way of
thinking, or satisfying an irritated customer - hesitate about doing
the natural thing, the impulsive thing. This is usually wrong.
Instead, turn to these pages and review the paragraphs you have
underscored. Then try these new ways and watch them achieve magic for
you.

7. Offer your spouse, your child or some business associate a dime or
a dollar every time he or she catches you violating a certain
principle. Make a lively game out of mastering these rules.

8. The president of an important Wall Street bank once described, in a
talk before one of my classes, a highly efficient system he used for
self-improvement. This man had little formal schooling; yet he had
become one of the most important financiers in America, and he
confessed that he owed most of his success to the constant application
of his homemade system. This is what he does, I'll put it in his own words as accurately as I can remember.

"For years I have kept an engagement book showing all the appointments I had during the day. My family never made any
plans for me on Saturday night, for the family knew that I devoted a
part of each Saturday evening to the illuminating process of
self-examination and review and appraisal. After dinner I went off by
myself, opened my engagement book, and thought over all the
interviews, discussions and meetings that had taken place during the
week. I asked myself 

'What mistakes did I make that time?' 'What did I do that was
right and in what way could I have improved my performance?' 'What
lessons can I learn from that experience?'

"I often found that this weekly review made me very unhappy. I was
frequently astonished at my own blunders. Of course, as the years
passed, these blunders became less frequent. Sometimes I was inclined
to pat myself on the back a little after one of these sessions. This
system of self-analysis, self-education, continued year after year,
did more for me than any other one thing I have ever attempted.

"It helped me improve my ability to make decisions - and it aided me
enormously in all my contacts with people. I cannot recommend it too
highly."

Why not use a similar system to check up on your application of the
principles discussed in this book? If you do, two things will result.

First, you will find yourself engaged in an educational process that
is both intriguing and priceless.

Second, you will find that your ability to meet and deal with people
will grow enormously.

9. You will find at the end of this book several blank pages on which
you should record your triumphs in the application of these
principles. Be specific. Give names, dates, results. Keeping such a
record will inspire you to greater efforts; and how fascinating these
entries will be when you chance upon them some evening years from now!

In order to get the most out of this book:

a. Develop a deep, driving desire to master the principles of human
relations,

b. Read each chapter twice before going on to the next one.

c. As you read, stop frequently to ask yourself how you can apply each
suggestion.

d. Underscore each important idea.

e. Review this book each month.

f. Apply these principles at every opportunity. Use this volume as a
working handbook to help you solve your daily problems.

g. Make a lively game out of your learning by offering some friend a
dime or a dollar every time he or she catches you violating one of
these principles.

h. Check up each week on the progress you are making. Ask yourself
what mistakes you have made, what improvement, what lessons you have
learned for the future.

i. Keep notes in the back of this book showing how and when you have
applied these principles.

** PART TWO Ways to Make People Like You
*** 1 DO THIS AND YOU'LL BE WELCOME ANYWHERE

Why read this book to find out how to win fi-iends? Why not study the
technique of the greatest winner of fi'iends the world has ever known?
Who is he? You may meet him tomorrow coming down the street. When you
get within ten feet of him, he will begin to wag his tail. If you stop
and pat him, he will almost jump out of his skin to show you how much
he likes you. And you know that behind this show of affection on his
part, there are no ulterior motives: he doesn't want to sell you any
real estate, and he doesn't want to marry you.

Did you ever stop to think that a dog is the only animal that doesn't
have to work for a living? A hen has to lay eggs, a cow has to give
milk, and a canary has to sing. But a dog makes his living by giving
you nothing but love.

When I was five years old, my father bought a little yellow-haired pup
for fifty cents. He was the light and joy of my childhood. Every
afternoon about four-thirty, he would sit in the front yard with his
beautiful eyes staring steadfastly at the path, and as soon as he
heard my voice or saw me swinging my dinner pail through the buck
brush, he was off like a shot, racing breathlessly up the hill to
greet me with leaps of joy and barks of sheer ecstasy.

Tippy was my constant companion for five years. Then one tragic night -
1 shall never forget it - he was killed within ten feet of my head,
killed by lightning. Tippy's death was the tragedy of my boyhood.

You never read a book on psychology, Tippy. You didn't need to. You
knew by some divine instinct that you can make more friends in two
months by becoming genuinely interested in other people than you can
in two years by trying to get other people interested in you. Let me
repeat that. You can make more friends in two months by becoming
interested in other people than you can in two years by trying to get
other people interested in you.

Yet I know and you know people who blunder through life trying to
wigwag other people into becoming interested in them.

Of course, it doesn't work. People are not interested

in you. They are not interested in me. They are interested

in themselves - morning, noon and after dinner.

The New York Telephone Company made a detailed study of telephone
conversations to find out which word is the most frequently used. You
have guessed it: it is the personal pronoun "L" "L" L" It was used
3,900 times in 500 telephone conversations. "L" "L" "L" "L" When you
see a group photograph that you are in, whose picture do you look for
first?

If we merely try to impress people and get people interested in us, we
will never have many true, sincere friends. Friends, real friends, are
not made that way.

Napoleon tried it, and in his last meeting with Josephine

he said: "Josephine, I have been as fortunate as

any man ever was on this earth; and yet, at this hour, you

are the only person in the world on whom I can rely."

And historians doubt whether he could rely even on

her.

Alfred Adler, the famous Viennese psychologist, wrote a book entitled
What Life Should Mean to You. In that book he says: "It is the
individual who is not interested in his fellow men who has the
greatest difficulties in life and provides the greatest injury to
others. It is from among such individuals that all human failures
spring."

You may read scores of erudite tomes on psychology without coming
across a statement more significant for you and for me. Adler's
statement is so rich with meaning that I am going to repeat it in
italics:

It is the individual who is not interested in his fellow men who has
the greatest difjculties in life and provides the greutest injury to
others. It is from umong such individuals that all humun failures
spring.

I once took a course in short-story writing at New York University,
and during that course the editor of a leading magazine talked to our
class. He said he could pick up any one of the dozens of stories that
drifted across his desk every day and after reading a few paragraphs
he

could feel whether or not the author liked people. "If the author
doesn't like people," he said, "people won't like his or her stories."

This hard-boiled editor stopped twice in the course of his talk on
fiction writing and apologized for preaching a sermon. "I am telling
you," he said, "the same things your preacher would tell you, but
remember, you have to be interested in people if you want to be a
successful writer of stories."

If that is true of writing fiction, you can be sure it is true of
dealing with people face-to-face.

I spent an evening in the dressing room of

Howard

Thurston the last time he appeared on

Broadway -

Thurston was the acknowledged dean of magicians. For forty

years he had traveled all over the world, time and again,

creating illusions, mystifying audiences, and making

people gasp with astonishment. More than 60 million

people had paid admission to his show, and he had made

almost $2 million in profit.

I asked Mr. Thurston to tell me the secret of his success. His
schooling certainly had nothing to do with it, for he ran away from
home as a small boy, became a hobo, rode in boxcars, slept in
haystacks, begged his food from door to door, and learned to read by
looking out of boxcars at signs along the railway.

Did he have a superior knowledge of magic? No, he

told me hundreds of books had been written about legerdemain

and scores of people knew as much about it as

he did. But he had two things that the others didn't have.

First, he had the ability to put his personality across the

footlights. He was a master showman. He knew human

nature. Everj^thing he did, every gesture, every intonation

of his voice, every lifting of an eyebrow had been

carefully rehearsed in advance, and his actions were

timed to split seconds. But, in addition to that, Thurston

had a genuine interest in people. He told me that many

magicians would look at the audience and say to themselves,

"Well, there is a bunch of suckers out there, a

bunch of hicks; I'll fool them all right." But Thurston's

method was totally different. He told me that every time he went on
stage he said to himself "I am gratefUl because these people come to
see me, They make it possible for me to make my living in a very
agreeable way. I'm going to give them the very best I possibly can."

He declared he never stepped in front of the footlights

without first saying to himself over and over: "I love my

audience. I love my audience." Ridiculous? Absurd?

You are privileged to think anything you like. I

am

merely passing it on to you without comment as a recipe

used by one of the most famous magicians of all time.

George Dyke of North Warren, Pennsylvania, was forced to retire from
his service station business after thirty years when a new highway was
constructed over the site of his station. It wasn't long before the
idle days of retirement began to bore him, so he started filling in
his time trying to play music on his old fiddle. Soon he was traveling
the area to listen to music and talk with many of the accomplished
fiddlers. In his humble and friendly way he became generally
interested in learning the background and interests of every musician
he met. Although he was not a great fiddler himself, he made many
friends in this pursuit. He attended competitions and soon became
known to the country music fans in the eastern part of the United
States as "Uncle George, the Fiddle Scraper from Kinzua County." When
we heard Uncle George, he was seventy-two and enjoying every minute of
his life. By having a sustained interest in other people, he created a
new life for himself at a time when most people consider their
productive years over.

That, too, was one of the secrets of Theodore Roosevelt's astonishing
popularity. Even his servants loved him. His valet, James E. Amos,
wrote a book about him entitled Theodore Roosevelt, Hero to His Valet.
In that book Amos relates this illuminating incident:

My wife one time asked the President about a bobwhite. She had never
seen one and he described it to her fully. Sometime later, the
telephone at our cottage rang. [Amos and his wife lived in a little
cottage on the Roosevelt estate at Oyster Bay.] My wife answered it
and it was Mr. Roosevelt himself He had called her, he said, to tell
her that there

was a bobwhite outside her window and that if she would look out she
might see it. Little things like that were so characteristic of him.
Whenever he went by our cottage, even though we were out of sight, we
would hear him call out: "Oo-oo-oo, Annie?" or "Oo-oo-oo, James!" It
was just a friendly greeting as he went by.

How could employees keep from liking a man like that? How could anyone
keep from liking him? Roosevelt called at the White House one day when
the President and Mrs. Taft were away. His honest liking for humble
people was shown by the fact that he greeted all the old White House
servants by name, even the scullery maids.

"When he saw Alice, the kitchen maid," writes Archie Butt, "he asked
her if she still made corn bread. Alice told him that she sometimes
made it for the servants, but no one ate it upstairs.

'"They show bad taste,' Roosevelt boomed, 'and I'll tell the President
so when I see him.'

"Alice brought a piece to him on a plate, and he went

over to the office eating it as he went and greeting gardeners

and laborers as he passed. . .

"He addressed each person just as he had addressed

them in the past. Ike Hoover, who had been head usher

at the White House for forty years, said with tears in his

eyes: 'It is the only happy day we had in nearly two

years, and not one of us would exchange it for a hundred-dollar

bill.'"

The same concern for the seemingly unimportant people helped sales
representative Edward M. Sykes, Jr., of Chatham, New Jersey, retain an
account. "Many years ago," he reported, "I called on customers for
Johnson and Johnson in the Massachusetts area. One account was a drug
store in Hingham. Whenever I went into this store I would always talk
to the soda clerk and sales clerk for a few minutes before talking to
the owner to obtain his order. One day I went up to the owner of the
store, and he told me to leave as he was not interested in buying J&J
products anymore because he felt they were concentrating their
activities on food and discount stores

to the detriment of the small drugstore. I left with my tail between
my legs and drove around the town ft)r several hours. Finally, I
decided to go back and try at least to explain our position to the
owner of the store.

"When I returned I walked in and as usual said hello to the soda clerk
and sales clerk. When I walked up to the owner, he smiled at me and
welcomed me back. He then gave me double the usual order, I looked at
him with surprise and asked him what had happened since my visit only
a few hours earlier. He pointed to the young man at the soda fountain
and said that after I had left, the boy had come over and said that I
was one of the few salespeople that called on the store that even
bothered to say hello to him and to the others in the store. He told
the owner that if any salesperson deserved his business, it was I. The
owner agreed and remained a loyal customer. I never forgot that to be
genuinely interested in other people is a most important quality for a
sales-person to possess - for any person, for that matter."

I have discovered from personal experience that one

can win the attention and time and cooperation of even

the most sought-after people by becoming genuinely interested

in them. Let me illustrate.

Years ago I conducted a course in fiction writing at the Brooklyn
Institute of Arts and Sciences, and we wanted such distinguished and
busy authors as Kathleen Norris, Fannie Hurst, Ida Tarbell, Albert
Payson Terhune and Rupert Hughes to come to Brooklyn and give us the
benefit of their experiences. So we wrote them, saying we admired
their work and were deeply interested in getting their advice and
learning the secrets of their success.

Each of these letters was signed by about a hundred and fifty
students. We said we realized that these authors were busy - too busy
to prepare a lecture. So we enclosed a list of questions for them to
answer about themselves and their methods of work. They liked that.
Who wouldn't like it? So they left their homes and traveled to
Brooklyn to give us a helping hand.

By using the same method, I persuaded Leslie M. Shaw, secretary of the
treasury in Theodore Roosevelt's cabinet; George W. Wickersham,
attorney general in

Taft's cabinet; William Jennings Bryan; Franklin D. Roosevelt and many
other prominent men to come to talk to the students of my courses in
public speaking.

All of us, be we workers in a factory, clerks in an office or even a
king upon his throne - all of us like people who admire us. Take the
German Kaiser, for example. At the close of World War I he was
probably the most savagely and universally despised man on this earth.
Even his own nation turned against him when he fled over into Holland
to save his neck. The hatred against him was so intense that millions
of people would have loved to tear him limb from limb or burn him at
the stake. In the midst of all this forest fire of fury, one little
boy wrote the Kaiser a simple, sincere letter glowing with kindliness
and admiration. This little boy said that no matter what the others
thought, he would always love Wilhelm as his Emperor. The Kaiser was
deeply touched by his letter and invited the little boy to come to see
him. The boy came, so did his mother - and the Kaiser married her.
That little boy didn't need to read a book on how to win friends and
influence people. He knew how instinctively.

If we want to make friends, let's put ourselves out to do things for
other people - things that require time, energy, unselfishness and
thoughtflilness. When the Duke of Windsor was Prince of Wales, he was
scheduled to tour South America, and before he started out on that
tour he spent months studying Spanish so that he could make public
talks in the language of the country; and the South Americans loved
him for it.

For years I made it a point to find out the birthdays of my friends.
How? Although I haven't the foggiest bit of faith in astrology, I
began by asking the other party whether he believed the date of one's
birth has anything to do with character and disposition. I then asked
him or her to tell me the month and day of birth. If he or she said
November 24, for example, I kept repeating to myself, "November 24,
November 24." The minute my friend's back was turned, I wrote down the
name and birthday and later would transfer it to a birthday book. At
the beginning of each year, I had these birthday dates scheduled in my
calendar pad so that they came to my attention automatically. When the
natal day arrived, there was my letter or telegram. What a hit it
made! I

was frequently the only person on earth who remembered.

If we want to make friends, let's greet people with animation and
enthusiasm. When somebody calls you on the telephone use the same
psychology. Say "Hello" in tones that bespeak how pleased YOU are to
have the person call. Many companies train their telephone operatars
to greet all callers in a tone of voice that radiates interest and
enthusiasm. The caller feels the company is concerned about them.
Let's remember that when we answer the telephone tomorrow.

Showing a genuine interest in others not only wins friends for you,
but may develop in its customers a loyalty to your company. In an
issue of the publication of the National Bank of North America of New
York, the following letter from Madeline Rosedale, a depositor, was
published: *

* Eagle, publication of the Natinnal Bank of North America, h-ew York,

March 31, 1978.

"I would like you to know how much I appreciate your staff Everyone is
so courteous, polite and helpful. What a pleasure it is, after waiting
on a long line, to have the teller greet you pleasantly.

"Last year my mother was hospitalized for five months. Frequently I
went to Marie Petrucello, a teller. She was concerned about my mother
and inquired about her progress."

Is there any doubt that Mrs. Rosedale will continue to use this bank?

Charles R. Walters, of one of the large banks in New York City, was
assigned to prepare a confidential report on a certain corporation. He
knew of only one person who possessed the facts he needed so urgently.
As Mr. Walters was ushered into the president's office, a young woman
stuck her head through a door and told the president that she didn't
have any stamps for him that day.

"I am collecting stamps for my twelve-year-old son," the president
explained to Mr. Walters.

Mr. Walters stated his mission and began asking questions.

The president was vague, general, nebulous. He

didn't want to talk, and apparently nothing could persuade

him to talk. The interview was brief and barren.

"Frankly, I didn't know what to do," Mr. Walters said as he related
the story to the class. "Then I remembered what his secretary had said
to him - stamps, twelve-year-old son. . . And I also recalled that the
foreign department of our bank collected stamps - stamps taken from
letters pouring in from every continent washed by the seven seas.

"The next afternoon I called on this man and sent in word that I had
some stamps for his boy. Was I ushered in with enthusiasm? Yes sir. He
couldn't have shaken my hand with more enthusiasm if he had been
running for Congress. He radiated smiles and good will. 'My George
will love this one,' he kept saying as he fondled the stamps. 'And
look at this! This is a treasure.'

"We spent half an hour talking stamps and looking at a picture of his
boy, and he then devoted more than an hour of his time to giving me
every bit of information I wanted - without my even suggesting that he
do it. He told me all he knew, and then called in his subordinates and
questioned them. He telephoned some of his associates. He loaded me
down with facts, figures, reports and correspondence. In the parlance
of newspaper reporters, I had a scoop."

Here is another illustration:

C. M. Knap hie, Jr., of Philadelphia had tried for years to sell fuel
to a large chain-store organization. But the chain-store company
continued to purchase its fiael from an out-of-town dealer and haul it
right past the door of Knaphle's office. Mr, Knaphle made a speech one
night before one of my classes, pouring out his hot wrath upon chain
stores, branding them as a curse to the nation.

And still he wondered why he couldn't sell them.

I suggested that he try different tactics. To put it

briefly, this is what happened. We staged a debate between

members of the course on whether the spread of

the chain store is doing the country more harm than good.

Knaphle, at my suggestion, took the negative side; he agreed to defend
the chain stores, and then went straight to an executive of the
chain-store organization that he despised and said: "I am not here to
try to sell fuel. I have come to ask you to do me a favor." He then
told about his debate and said, "I have come to you for help because I
can't think of anyone else who would be more capable of giving me the
facts I want. I'm anxious to win this debate, and I'll deeply
appreciate whatever help you can give me."

Here is the rest of the story in Mr. Knaphle's own words:

I had asked this man for precisely one minute of his time. It was with
that understanding that he consented to see me. After I had stated my
case, he motioned me to a chair and talked to me for exactly one hour
and forty-seven minutes. He called in another executive who had
written a book on chain stores. He wrote to the National Chain Store
Association and secured for me a copy of a debate on the subject. He
feels that the chain store is rendering a real service to humanity. He
is proud of what he is doing for hundreds of communities. His eyes
fairly glowed as he talked, and I must confess that he opened my eyes
to things I had never even dreamed of He changed my whole mental
attitude. As I was leaving, he walked with me to the door, put his arm
around my shoulder, wished me well in my debate, and asked me to stop
in and see him again and let him know how I made out. The last words
he said to me were: "Please see me again later in the spring. I should
like to place an order with you for fuel."

To me that was almost a miracle. Here he was offering to buy fuel
without my even suggesting it. I had made more headway in two hours by
becoming genuinely interested in him and his problems than I could
have made in ten years trying to get him interested in me and my
product.

You didn't discover a new truth, Mr. Knaphle, for a long time ago, a
hundred years before Christ was born a famous old Roman poet,
Publilius Syrus, remarked; "We are interested in others when they are
interested in us."

A show of interest, as with every other principle of human relations,
must be sincere. It must pay off not only for the person showing the
interest, but for the person receiving the attention. It is a two-way
street-both parties benefit.

Martin Ginsberg, who took our Course in Long Island New York, reported
how the special interest a nurse took in him profoundly affected his
life:

"It was Thanksgiving Day and I was ten years old. I

was in a welfare ward of a city hospital and was scheduled

to undergo major orthopedic surgery the next day.

I knew that I could only look forward to months of confinement,

convalescence and pain. My father was dead;

my mother and I lived alone in a small apartment and

we were on welfare. My mother was unable to visit me

that day.

"As the day went on, I became overwhelmed with the feeling of
loneliness, despair and fear. I knew my mother was home alone worrying
about me, not having anyone to be with, not having anyone to eat with
and not even having enough money to afford a Thanksgiving Day dinner.

"The tears welled up in my eyes, and I stuck my head under the pillow
and pulled the covers over it, I cried silently, but oh so bitterly,
so much that my body racked with pain.

"A young student nurse heard my sobbing and came over to me. She took
the covers off my face and started wiping my tears. She told me how
lonely she was, having to work that day and not being able to be with
her family. She asked me whether I would have dinner with her. She
brought two trays of food: sliced turkey, mashed a potatoes, cranberry
sauce and ice cream for dessert. She talked to me and tried to calm my
fears. Even though she was scheduled to go off duty at 4 P.M., she
stayed on her own time until almost 11 P.M. She played games with me,
talked to me and stayed with me until I finally fell asleep.

"Many Thanksgivings have come and gone since I

was ten, but one never passes without me remembering that particular
one and my feelings of frustration, fear, loneliness and the warmth
and tenderness of the stranger that somehow made it all bearable."

If you want others to like you, if you want to develop real
friendships, if you want to help others at the same time as you help
yourself, keep this principle in mind:

PRINCIPLE 1

Become genuinely interested in other people.
** 2 A SIMPLE WAY TO MAKE A GOOD FIRST IMPRESSION

At a dinner party in New York, one of the guests, a woman who had
inherited money, was eager to make a pleasing impression on everyone.
She had squandered a modest fortune on sables, diamonds and pearls.
But she hadn't done anything whatever about her face. It radiated
sourness and selfishness. She didn't realize what everyone knows:
namely, that the expression one wears on one's face is far more
important than the clothes one wears on one's back.

Charles Schwab told me his smile had been worth a

million dollars. And he was probably understating the

truth. For Schwab's personality, his charm, his ability to

make people like him, were almost wholly responsible

for his extraordinary success; and one of the most delightful

factors in his personality was his captivating

smile.

Actions speak louder than words, and a smile says, "I like you. You
make me happy. I am glad to see you." That is why dogs make such a
hit. They are so glad to

see us that they almost jump out of their skins. So, naturally, we are
glad to see them.

A baby's smile has the same effect.

Have you ever been in a doctor's waiting room and looked around at all
the glum faces waiting impatiently to be seen? Dr, Stephen K. Sproul,
a veterinarian in Raytown, Missouri, told of a typical spring day when
his waiting room was full of clients waiting to have their pets
inoculated. No one was talking to anyone else, and all were probably
thinking of a dozen other things they would rather be doing than
"wasting time" sitting in that office. He told one of our classes:
"There were six or seven clients waiting when a young woman came in
with a nine-month-old baby and a kitten. As luck would have it, she
sat down next to a gentleman who was more than a little distraught
about the long wait for service. The next thing he knew, the baby just
looked up at him with that great big smile that is so characteristic
of babies. What did that gentleman do? Just what you and I would do,
of course; he-smiled back at the baby. Soon he struck up a
conversation with the woman about her baby and his grandchildren, and
soon the entire reception room joined in, and the boredom and tension
were converted into a pleasant and enjoyable experience."

An insincere grin? No. That doesn't fool anybody. We know it is
mechanical and we resent it. I am talking about a real smile, a
heartwarming smile, a smile that comes from within, the kind of smile
that will bring a good price in the marketplace.

Professor James V. McConnell, a psychologist at the University of
Michigan, expressed his feelings about a smile. "People who smile," he
said, "tend to manage teach and sell more effectively, and to raise
happier children. There's far more information in a smile than a
frown. That's why encouragement is a much more effective teaching
device than punishment."

The employment manager of a large New York department store told me
she would rather hire a sales clerk who hadn't finished grade school,
if he or she has a pleasant smile, than to hire a doctor of philosophy
with a somber face.

The effect of a smile is powerful - even when it is unseen. Telephone
companies throughout the United States have a program called "phone
power" which is offered to employees who use the telephone for selling
their services or products. In this program they suggest that you
smile when talking on the phone. Your "smile" comes through in your
voice.

Robert Cryer, manager of a computer department for a Cincinnati, Ohio,
company, told how he had successfully found the right applicant for a
hard-to-fill position:

"I was desperately trying to recruit a Ph.D. in computer

science for my department. I finally located a

young man with ideal qualifications who was about to

be graduated from Purdue University. After several

phone conversations I learned that he had several offers

from other companies, many of them larger and better

known than mine. I was delighted when he accepted my

offer. After he started on the job, I asked him why he

had chosen us over the others. He paused for a moment

and then he said: 'I think it was because managers in the

other companies spoke on the phone in a cold, business-like

manner, which made me feel like just another business

transaction. Your voice sounded as if you were glad

to hear from me . . . that you really wanted me to be part

of your organization. ' You can be assured, I am still answering

my phone with a smile."

The chairman of the board of directors of one of the largest rubber
companies 'in the United States told me that, according to his
observations, people rarely succeed at anything unless they have fun
doing it. This industrial leader doesn't put much faith in the old
adage that hard work alone is the magic key that will unlock the door
to our desires, "I have known people," he said, "who succeeded because
they had a rip-roaring good time conducting their business. Later, I
saw those people change as the flm became work. The business had grown
dull. They lost all joy in it, and they failed."

You must have a good time meeting people if you expect them to have a
good time meeting you.

I have asked thousands of business people to smile at

someone every hour of the day for a week and then come to class and
talk about the results. How did it work? Let's see. . . Here is a
letter from William B. Steinhardt, a New York stockbroker. His case
isn't isolated. In fact, it is typical of hundreds of cases.

"1 have been married for over eighteen years," wrote Mr. Steinhardt,
"and in all that time I seldom smiled at my wife or spoke two dozen
words to her from the time I got up until I was ready to leave for
business. I was one of the worst grouches who ever walked down
Broadway.

"When you asked me to make a talk about my experience with smiles, I
thought I would try it for a week. So the next morning, while combing
my hair, I looked at my glum mug in the mirror and said to myself,
'Bill, you are going to wipe the scowl off that sour puss of yours
today. You are going to smile. And you are going to begin right now.'
As I sat down to breakfast, I greeted my wife with a 'Good morning, my
dear,' and smiled as I said it.

"You warned me that she might be surprised. Well, you underestimated
her reaction. She was bewildered. She was shocked. I told her that in
the future she could expect this as a regular occurrence, and I kept
it up every morning.

"This changed attitude of mine brought more happiness into our home in
the two months since I started than there was during the last year.

"As I leave for my office, I greet the elevator operator in the
apartment house with a 'Good morning' and a smile, I greet the doorman
with a smile. I smile at the cashier in the subway booth when I ask
for change. As I stand on the floor of the Stock Exchange, I smile at
people who until recently never saw me smile.

"I soon found that everybody was smiling back at me,

I treat those who come to me with complaints or grievances

in a cheerful manner, I smile as I listen to them

and I find that adjustments are accomplished much easier.

I find that smiles are bringing me dollars, many dollars

every day.

"I share my office with another broker. One of his clerks is a hkable
young chap, and I was so elated about the results I was getting that I
told him recently about my new philosophy of human relations. He then
confessed that when I first came to share my office with his firm he
thought me a terrible grouch - and only recently changed his mind. He
said I was really human when I smiled.

"I have also eliminated criticism from my system. I give appreciation
and praise now instead of condemnation. I have stopped talking about
what I want. I am now trying to see the other person's viewpoint. And
these things have literally revolutionized my life. I am a totally
different man, a happier man, a richer man, richer in friendships and
happiness - the only things that matter much after all."

You don't feel like smiling? Then what? Two things. First, force
yourself to smile. If you are alone, force yourself to whistle or hum
a tune or sing. Act as if you were already happy, and that will tend
to make you happy. Here is the way the psychologist and philosopher
William James put it:

"Action seems to follow feeling, but really action and feeling go
together; and by regulating the action, which is under the more direct
control of the will, we can indirectly regulate the feeling, which is
not.

"Thus the sovereign voluntary path to cheerftilness, if our
cheerfulness be lost, is to sit up cheerfully and to act and speak as
if cheerfulness were already there. . . ."

Every body in the world is seeking happiness - and there is one sure
way to find it. That is by controlling your thoughts. Happiness
doesn't depend on outward conditions. It depends on inner conditions.

It isn't what you have or who you are or where you are or what you are
doing that makes you happy or unhappy. It is what you think about it.
For example, two people may be in the same place, doing the same
thing; both may have about an equal amount of money and prestige - and
yet one may be miserable and the other happy. Why? Because of a
different mental attitude. I have seen

just as many happy faces among the poor peasants toiling with their
primitive tools in the devastating heat of the tropics as I have seen
in air-conditioned offices in New York, Chicago or Los Angeles.

"There is nothing either good or bad," said Shakespeare, "but thinking
makes it so."

Abe Lincoln once remarked that "most folks are about as happy as they
make up their minds to be." He was right. I saw a vivid illustration
of that truth as I was walking up the stairs of the Long Island
Railroad station in New York. Directly in front of me thirty or forty
crippled boys on canes and crutches were struggling up the stairs. One
boy had to be carried up. I was astonished at their laughter and
gaiety. I spoke about it to one of the men in charge of the boys. "Oh,
yes," he said, "when a boy realizes that he is going to be a cripple
for life, he is shocked at first; but after he gets over the shock, he
usually resigns himself to his fate and then becomes as happy as
normal boys."

I felt like taking my hat off to those boys. They taught me a lesson I
hope I shall never forget.

Working all by oneself in a closed-off room in an office not only is
lonely, but it denies one the opportunity of making friends with other
employees in the company. Senora Maria Gonzalez of Guadalajara,
Mexico, had such a job. She envied the shared comradeship of other
people in the company as she heard their chatter and laughter. As she
passed them in the hall during the first weeks of her employment, she
shyly looked the other way.

After a few weeks, she said to herself, "Maria, you can't expect those
women to come to you. You have to go out and meet them. " The next
time she walked to the water cooler, she put on her brightest smile
and said, "Hi, how are you today" to each of the people she met. The
effect was immediate. Smiles and hellos were returned, the hallway
seemed brighter, the job friendlier.

Acquaintanceships developed and some ripened into friendships. Her job
and her life became more pleasant and interesting.

Peruse this bit of sage advice from the essayist and publisher Elbert
Hubbard - but remember, perusing it won't do you any good unless you
apply it:

Whenever you go out-of-doors, draw the chin in, carry the crown of the
head high, and fill the lungs to the utmost; drink in the sunshine;
greet your friends with a smile, and put soul into every handclasp. Do
not fear being misunderstood and do not waste a minute thinking about
your enemies. Try to fix firmly in your mind what you would like to
do; and then, without veering off direction, you will move straight to
the goal. Keep your mind on the great and splendid things you would
like to do, and then, as the days go gliding away, you will find
yourself unconsciously seizing upon the opportunities that are
required for the fulfillment of your desire, just as the coral insect
takes from the running tide the element it needs. Picture in your mind
the able, earnest, useful person you desire to be, and the thought you
hold is hourly transforming you into that particular individual. . . .
Thought is supreme. Preserve a right mental attitude -the attitude of
courage, frankness, and good cheer. To think rightly is to create. All
things come through desire and every sincere prayer is answered. We
become like that on which our hearts are fixed. Carry your chin in and
the crown of your head high. We are gods in the chrysalis.

The ancient Chinese were a wise lot - wise in the ways of the world;
and they had a proverb that you and I ought to cut out and paste
inside our hats. It goes like this: "A man without a smiling face must
not open a shop."

Your smile is a messenger of your good will. Your smile brightens the
lives of all who see it. To someone who has seen a dozen people frown,
scowl or turn their faces away, your smile is like the sun breaking
through the clouds. Especially when that someone is under pressure
from his bosses, his customers, his teachers or parents or children, a
smile can help him realize that all is not hopeless - that there is
joy in the world.

Some years ago, a department store in New York City, in recognition of
the pressures its sales clerks were under during the Christmas rush,
presented the readers of its advertisements with the following homely
philosophy:

THE VALUE OF A SMILE AT CHRISTMAS

It costs nothing, but creates much.

It enriches those who receive, without impoverishing those

who give. It happens in a flash and the memory of it sometimes lasts

forever. None are so rich they can get along without it, and none so

poor but are richer for its benefits. It creates happiness in the
home, fosters good will in a

business, and is the countersign of friends. It is rest to the weary,
daylight to the discouraged, sunshine

to the sad, and Nature's best antidote fee trouble. Yet it cannot be
bought, begged, borrowed, or stolen, for it

is something that is no earthly good to anybody till it is

given away. And if in the last-minute rush of Christmas buying some of

our salespeople should be too tired to give you a smile,

may we ask you to leave one of yours? For nobody needs a smile so much
as those who have none

left to give!

PRINCIPLE 2 Smile.
** 3 IF YOU DON'T DO THIS, YOU ARE HEADED FOR TROUBLE

Back in 1898, a tragic thing happened in Rockland County, New York. A
child had died, and on this particular day the neighbors were
preparing to go to the funeral.

Jim Farley went out to the barn to hitch up his

horse. The ground was covered with snow, the air was

cold and snappy; the horse hadn't been exercised for days; and as he
was led out to the watering trough, he wheeled playfully, kicked both
his heels high in the air, and killed Jim Farley. So the little
village of Stony Point had two funerals that week instead of one.

Jim Farley left behind him a widow and three boys, and a few hundred
dollars in insurance.

His oldest boy, Jim, was ten, and he went to work in a

brickyard, wheeling sand and pouring it into the molds

and turning the brick on edge to be dried by the sun.

This boy Jim never had a chance to get much education.

But with his natural geniality, he had a flair for making

people like him, so he went into politics, and as the

years went by, he developed an uncanny ability for remembering

people's names.

He never saw the inside of a high school; but before he was forty-six
years of age, four colleges had honored him with degrees and he had
become chairman of the Democratic National Committee and Postmaster
General of the United States.

I once interviewed Jim Farley and asked him the secret of his success.
He said, "Hard work," and I said, "Don't be fiinny."

He then asked me what I thought was the reason for his success. I
replied: "I understand you can call ten thousand people by their first
names."

"No. You are wrong, " he said. "I can call fifty thousand people by
their first names."

Make no mistake about it. That ability helped Mr. Farley put Franklin
D. Roosevelt in the White House when he managed Roosevelt's campaign
in 1932.

During the years that Jim Farley traveled as a salesman for a gypsum
concern, and during the years that he held office as town clerk in
Stony Point, he built up a system for remembering names.

In the beginning, it was a very simple one. Whenever

he met a new acquaintance, he found out his or her complete

name and some facts about his or her family, business and pohtical
opinions. He fixed all these facts well in mind as part of the
picture, and the next time he met that person, even if it was a year
later, he was able to shake hands, inquire after the family, and ask
about the hollyhocks in the backyard. No wonder he developed a
following!

For months before Roosevelt's campaign for President began, Jim Farley
wrote hundreds of letters a day to people all over the western and
northwestern states. Then he hopped onto a train and in nineteen days
covered twenty states and twelve thousand miles, traveling by buggy,
train, automobile and boat. He would drop into town, meet his people
at lunch or breakfast, tea or dinner, and give them a "heart-to-heart
talk." Then he'd dash off again on another leg of his journey.

As soon as he arrived back East, he wrote to one person in each town
he had visited, asking for a list of all the guests to whom he had
talked. The final list contained thousands and thousands of names; yet
each person on that list was paid the subtle fiattery of getting a
personal letter from James Farley. These letters began "Dear Bill" or
"Dear Jane," and they were always signed "Jim."

Jim Farley discovered early in life that the average person is more
interested in his or her own name than in all the other names on earth
put together. Remember that name and call it easily, and you have paid
a subtle and very effective compliment. But forget it or misspell it -
and you have placed yourself at a sharp disadvantage. For example, I
once organized a public-speaking course in Paris and sent form letters
to all the American residents in the city. French typists with
apparently little knowledge of English filled in the names and
naturally they made blunders. One man, the manager of a large American
bank in Paris, wrote me a scathing rebuke because his name had been
misspelled.

Sometimes it is difficult to remember a name, particularly if it is
hard to pronounce. Rather than even try to learn it, many people
ignore it or call the person by an easy nickname. Sid Levy called on a
customer for some time whose name was Nicodemus Papadoulos. Most

people just called him "Nick." Levy told us: "I made a special effort
to say his name over several times to myself before I made my call.
When I greeted him by his full name: 'Good afternoon, Mr. Nicodemus
Papadoulos,' he was shocked. For what seemed like several minutes
there was no reply from him at all. Finally, he said with tears
rolling down his cheeks, 'Mr. Levy, in all the fifteen years I have
been in this country, nobody has ever made the effort to call me by my
right name.' "

What was the reason for Andrew Carnegie's success?

He was called the Steel King; yet he himself knew little about the
manufacture of steel. He had hundreds of people working for him who
knew far more about steel than he did.

But he knew how to handle people, and that is what

made him rich. Early in life, he showed a flair for organization,

a genius for leadership. By the time he was ten,

he too had discovered the astounding importance people

place on their own name. And he used that discovery to

win cooperation. To illustrate: When he was a boy back

in Scotland, he got hold of a rabbit, a mother rabbit.

Presto! He soon had a whole nest of little rabbits - and

nothing to feed them. But he had a brilliant idea. He told

the boys and girls in the neighborhood that if they would

go out and pull enough clover and dandelions to feed

the rabbits, he would name the bunnies in their honor.

The plan worked like magic, and Carnegie never forgot it.

